// Comprehensive UK bereavement notification contacts
// Research date: 2026-03-14
// Used to build dedicated organisation pages on HelpAfterLoss

export interface BereavementContact {
  name: string
  category: 'bank' | 'building-society' | 'energy' | 'telecoms' | 'water' | 'insurance' | 'government'
  parentGroup?: string
  bereavementPhone?: string
  bereavementPhoneHours?: string
  internationalPhone?: string
  bereavementEmail?: string
  bereavementUrl: string
  onlineFormUrl?: string
  postalAddress?: string
  howToNotify: string[]
  documentsRequired: string[]
  jointAccountProcess?: string
  soleAccountProcess?: string
  typicalTimeline?: string
  specialForms?: string[]
  probateThreshold?: string
  additionalNotes?: string[]
  slug: string
}

export const bereavementContacts: BereavementContact[] = [
  // ============================================================
  // BANKS
  // ============================================================
  {
    name: 'Barclays',
    category: 'bank',
    bereavementPhone: '0800 068 2238',
    bereavementPhoneHours: 'Mon-Fri 8am-5pm, Sat 9am-2pm',
    bereavementUrl: 'https://www.barclays.co.uk/help/estates-bereavement/customer-death/',
    onlineFormUrl: 'https://formsdss-live.uk.barclays/bereavementsform/service/container/forms/bereavementsform/index.html?AUTH=N',
    postalAddress: 'Bereavement Service Centre, Barclays Bank PLC, Leicester, LE87 2BB',
    howToNotify: [
      'Phone: Call 0800 068 2238',
      'Online: Complete the bereavement notification form',
      'Post: Write to Bereavement Service Centre, Leicester, LE87 2BB',
      'Video call or branch appointment can be booked',
      'Death Notification Service (notifies multiple banks at once)',
    ],
    documentsRequired: [
      'Death certificate (original or certified copy)',
      'Your photo ID (passport or driving licence)',
      'Specific documents confirmed during your appointment',
    ],
    jointAccountProcess: 'Joint accounts are typically transferred to the surviving account holder. Contact Barclays for specifics during your appointment.',
    soleAccountProcess: 'Sole accounts are frozen. Barclays will inform all relevant divisions including Barclaycard, Business, and Wealth.',
    typicalTimeline: 'Varies depending on documentation. Barclays will discuss timescales during your video call or branch appointment.',
    specialForms: ['Bereavement notification form (online)'],
    additionalNotes: [
      'One notification covers all Barclays products including Barclaycard, Business, and Wealth',
      'Barclays Partner Finance has a separate number: 0800 1522 888',
    ],
    slug: 'barclays',
  },
  {
    name: 'HSBC',
    category: 'bank',
    bereavementPhone: '0800 085 1992',
    bereavementPhoneHours: 'Mon-Fri 8:30am-6pm, Sat 9am-2pm',
    internationalPhone: '+44 (0)114 252 0249',
    bereavementUrl: 'https://www.hsbc.co.uk/help/life-events/bereavement/',
    onlineFormUrl: 'https://www.hsbc.co.uk/help/life-events/bereavement/',
    howToNotify: [
      'Online: Use the bereavement portal (quickest method) to submit notification and upload documents',
      'Phone: Call 0800 085 1992',
      'Branch: Visit any HSBC branch in person',
      'Death Notification Service',
    ],
    documentsRequired: [
      'Death certificate (original or certified copy)',
      'Will (if available)',
      'Grant of Probate (if applicable)',
      'Photo ID of person dealing with estate (if not an HSBC customer)',
      'Completed closure form',
    ],
    jointAccountProcess: 'Joint accounts are updated to the surviving account holder\'s name. The surviving holder can continue using the account.',
    soleAccountProcess: 'Sole accounts are frozen to stop withdrawals, but money can still be paid in. HSBC informs all relevant departments.',
    typicalTimeline: 'HSBC notes processing times may vary. A reference number is provided after initial notification for tracking.',
    specialForms: ['Account closure form', 'Bereavement notification (via online portal)'],
    additionalNotes: [
      'You receive a reference number after initial submission to track and upload additional documents later',
      'HSBC bereavement support guide available as PDF download',
    ],
    slug: 'hsbc',
  },
  {
    name: 'Lloyds Bank',
    category: 'bank',
    parentGroup: 'Lloyds Banking Group',
    bereavementPhone: '0800 096 8560',
    bereavementPhoneHours: 'Mon-Fri 9am-5pm',
    internationalPhone: '+44 (0)1733 286 482',
    bereavementUrl: 'https://www.lloydsbank.com/help-guidance/life-events/bereavement.html',
    onlineFormUrl: 'https://www.lloydsbank.com/help-guidance/life-events/bereavement.html',
    howToNotify: [
      'Phone: Call 0800 096 8560 (Specialist Bereavement Team)',
      'Branch: Visit any Lloyds Bank branch',
      'Post: Send documents by recorded delivery',
      'Death Notification Service',
    ],
    documentsRequired: [
      'Death certificate (original or certified copy)',
      'Your photo ID or confirmation of your Lloyds account details',
      'Grant of Probate (usually only if accounts exceed £50,000)',
    ],
    jointAccountProcess: 'With right of survivorship: funds automatically transfer to surviving holder after death certificate provided. Without right of survivorship: deceased\'s share treated as part of estate.',
    soleAccountProcess: 'Sole accounts are frozen. Funeral invoices may receive priority payment from the estate funds.',
    typicalTimeline: 'Account closure can take up to 6 weeks. Probate-related processing takes longer.',
    probateThreshold: '£50,000',
    specialForms: ['Bereavement notification form'],
    additionalNotes: [
      'Part of Lloyds Banking Group (also covers Halifax, Bank of Scotland, Scottish Widows)',
      'Probate enquiry line: 0800 015 0012 (8am-8pm, 7 days a week)',
    ],
    slug: 'lloyds-bank',
  },
  {
    name: 'Halifax',
    category: 'bank',
    parentGroup: 'Lloyds Banking Group',
    bereavementPhone: '0800 028 1057',
    bereavementPhoneHours: '8am-8pm, 7 days a week',
    internationalPhone: '+44 (0)1733 261 630',
    bereavementUrl: 'https://www.halifax.co.uk/helpcentre/support-and-wellbeing/life-events/bereavement/bereavement-notification-form.html',
    onlineFormUrl: 'https://www.halifax.co.uk/helpcentre/life-events/bereavement/bereavement-notification-form.html',
    howToNotify: [
      'Phone: Call 0800 028 1057',
      'Online: Complete the 8-step bereavement notification questionnaire',
      'Branch: Book an appointment at any of 553+ branches',
      'Death Notification Service',
    ],
    documentsRequired: [
      'Death certificate or proof of death document',
      'Grant of Probate (if accounts exceed £50,000)',
      'Photo ID of executor/representative',
    ],
    jointAccountProcess: 'Joint accounts transferred to surviving account holder. Surviving holder retains access.',
    soleAccountProcess: 'Accounts frozen. Standing orders and Direct Debits cancelled. Debit, savings and credit cards cancelled. Online banking removed.',
    typicalTimeline: 'Account closure may take up to 6 weeks.',
    specialForms: ['Bereavement notification form (online questionnaire)'],
    additionalNotes: [
      'Part of Lloyds Banking Group',
      'Alternative probate helpline: 0800 015 0012',
    ],
    slug: 'halifax',
  },
  {
    name: 'Bank of Scotland',
    category: 'bank',
    parentGroup: 'Lloyds Banking Group',
    bereavementPhone: '0345 835 5641',
    bereavementPhoneHours: 'Mon-Fri 9am-5pm',
    internationalPhone: '+44 (0)131 203 3138',
    bereavementUrl: 'https://www.bankofscotland.co.uk/helpcentre/life-events/bereavement.html',
    onlineFormUrl: 'https://www.bankofscotland.co.uk/helpcentre/life-events/bereavement/bereavement-notification-form.html',
    howToNotify: [
      'Phone: Call 0345 835 5641 (Telephone Banking)',
      'Online: Complete the bereavement notification form',
      'Branch: Visit any Bank of Scotland branch',
      'If bank named as executor: Call Estates Administration on 0800 056 0171',
    ],
    documentsRequired: [
      'Death certificate (original or certified copy)',
      'Completed bereavement form',
      'Grant of Probate / Certificate of Confirmation (Scotland) if required',
    ],
    jointAccountProcess: 'Joint accounts transferred to surviving account holder.',
    soleAccountProcess: 'Sole accounts frozen pending estate administration.',
    typicalTimeline: 'Varies depending on estate complexity.',
    specialForms: ['Bank of Scotland bereavement form (5 pages)'],
    additionalNotes: [
      'Part of Lloyds Banking Group',
      'Estates Administration Service: 0800 056 0171',
    ],
    slug: 'bank-of-scotland',
  },
  {
    name: 'Scottish Widows',
    category: 'insurance',
    parentGroup: 'Lloyds Banking Group',
    bereavementPhone: '0345 601 4179',
    bereavementPhoneHours: 'Mon-Fri 9am-5pm',
    bereavementEmail: 'mailbox.estates@scottishwidows.co.uk',
    bereavementUrl: 'https://www.scottishwidows.co.uk/contact-us/bereavement.html',
    onlineFormUrl: 'https://extranet.secure.scottishwidows.co.uk/consumer/forms/contact_us/bereavement-claim-form',
    postalAddress: 'The Bereavement Team, PO Box 28015, 15 Dalkeith Road, Edinburgh, EH16 5WL',
    howToNotify: [
      'Phone: Call 0345 601 4179',
      'Online: Complete the bereavement claim form',
      'Email: Send death certificate to mailbox.estates@scottishwidows.co.uk',
      'Post: Write to The Bereavement Team, PO Box 28015, Edinburgh, EH16 5WL',
    ],
    documentsRequired: [
      'Death certificate (certified copy, photo or PDF accepted by email)',
      'Your name and telephone number',
      'Deceased\'s name, date of birth, and address',
      'Any policy number(s)',
    ],
    jointAccountProcess: 'Depends on policy type. Contact for specific guidance.',
    soleAccountProcess: 'Policy frozen pending claim assessment.',
    typicalTimeline: 'Multiple policies can be settled at different times.',
    specialForms: ['Bereavement claim form'],
    additionalNotes: [
      'Part of Lloyds Banking Group',
      'One notification covers all Scottish Widows policies',
    ],
    slug: 'scottish-widows',
  },
  {
    name: 'NatWest',
    category: 'bank',
    parentGroup: 'NatWest Group',
    bereavementPhone: '0800 161 5903',
    bereavementPhoneHours: 'Mon-Fri 9am-5pm (excl. bank holidays)',
    internationalPhone: '+44 (0)1204 684 658',
    bereavementUrl: 'https://www.natwest.com/support-centre/dealing-with-difficult-times/bereavement.html',
    onlineFormUrl: 'https://www.natwest.com/support-centre/dealing-with-difficult-times/bereavement.html',
    howToNotify: [
      'Online: Complete the digital bereavement notification (quickest method)',
      'Phone: Call 0800 161 5903',
      'Webchat: Available 8am-5pm Mon-Fri',
      'Branch: Visit any NatWest, RBS, or Ulster Bank branch',
      'Death Notification Service',
      'Relay UK: 18001 0800 161 5903',
    ],
    documentsRequired: [
      'Death certificate',
      'Will or Codicil',
      'Grant of Representation (England & Wales) or Certificate of Confirmation (Scotland)',
      'Completed Account Closure Form (signed by next of kin or executor)',
      'Documents from outside UK must include certified English translations',
    ],
    jointAccountProcess: 'Joint accounts updated to surviving account holder\'s name. Surviving holder can continue using the account normally.',
    soleAccountProcess: 'Sole accounts are "protected" immediately: no money moves in or out.',
    typicalTimeline: 'Condolence letter with BER reference number sent after notification. Processing varies by documentation completeness, typically several weeks.',
    specialForms: ['Account Closure Form'],
    additionalNotes: [
      'Part of NatWest Group (also covers RBS and Ulster Bank)',
      'Reference number starts with "BER"',
      'MyRewards must be claimed within 90 days of account closing',
      'Funeral invoices receive priority payment from deceased\'s funds',
      'Executor accounts can be opened with proper court documents',
    ],
    slug: 'natwest',
  },
  {
    name: 'Royal Bank of Scotland',
    category: 'bank',
    parentGroup: 'NatWest Group',
    bereavementPhone: '0800 161 5904',
    bereavementPhoneHours: 'Mon-Fri 9am-5pm (excl. bank holidays)',
    internationalPhone: '+44 (0)1204 684 659',
    bereavementUrl: 'https://www.rbs.co.uk/life-moments/bereavement.html',
    onlineFormUrl: 'https://www.rbs.co.uk/life-moments/bereavement.html',
    howToNotify: [
      'Online: Use the digital bereavement notification service (quickest)',
      'Phone: Call 0800 161 5904',
      'Branch: Visit any RBS, NatWest, or Ulster Bank branch',
      'Death Notification Service',
    ],
    documentsRequired: [
      'Death certificate',
      'Will or Codicil',
      'Grant of Representation / Certificate of Confirmation',
      'Completed Account Closure Form',
    ],
    jointAccountProcess: 'Joint accounts updated to surviving account holder\'s name.',
    soleAccountProcess: 'Sole accounts protected immediately upon notification.',
    typicalTimeline: 'Same process as NatWest Group. Condolence letter with BER reference issued.',
    specialForms: ['Account Closure Form'],
    additionalNotes: [
      'Part of NatWest Group',
      'Same process and forms as NatWest',
    ],
    slug: 'royal-bank-of-scotland',
  },
  {
    name: 'Ulster Bank',
    category: 'bank',
    parentGroup: 'NatWest Group',
    bereavementPhone: '0800 096 3612',
    bereavementPhoneHours: 'Mon-Fri 9am-5pm',
    internationalPhone: '+44 151 494 1260',
    bereavementUrl: 'https://www.ulsterbank.co.uk/help-and-support/bereavement.html',
    postalAddress: 'Ulster Bank Everyday Banking Operations, 11-16 Donegall Square East, Belfast, BT1 5UB',
    howToNotify: [
      'Phone: Call 0800 096 3612',
      'Branch: Visit any Ulster Bank, NatWest, or RBS branch',
      'Post: Write to Ulster Bank Everyday Banking Operations, Belfast, BT1 5UB',
      'Death Notification Service',
    ],
    documentsRequired: [
      'Death certificate',
      'Will or Codicil',
      'Grant of Representation / Certificate of Confirmation',
      'Completed Account Closure Form',
    ],
    jointAccountProcess: 'Joint accounts updated to surviving account holder\'s name.',
    soleAccountProcess: 'Sole accounts protected immediately upon notification.',
    typicalTimeline: 'Same process as NatWest Group.',
    specialForms: ['Account Closure Form'],
    additionalNotes: [
      'Part of NatWest Group',
      'Same process as NatWest and RBS',
    ],
    slug: 'ulster-bank',
  },
  {
    name: 'Santander',
    category: 'bank',
    bereavementPhone: '0800 587 5870',
    bereavementPhoneHours: 'Mon-Fri 8am-6pm, Sat 9am-2pm',
    internationalPhone: '01908 520814 (option 3)',
    bereavementUrl: 'https://www.santander.co.uk/personal/support/customer-support/bereavement',
    onlineFormUrl: 'https://bereavement-online.santander.co.uk',
    postalAddress: 'Santander Bereavement Operations, Sunderland, SR43 4FJ',
    howToNotify: [
      'Phone: Call 0800 587 5870 (Bereavement Assist)',
      'Online: Complete form at bereavement-online.santander.co.uk',
      'Post: Send Bereavement Instruction Form to Sunderland, SR43 4FJ',
      'Branch: Visit any Santander branch',
      'Death Notification Service',
    ],
    documentsRequired: [
      'Death certificate (original, certified copy, or photocopy)',
      'Your photo ID (passport or UK/EEA photocard driving licence)',
      'Grant of Representation (if sole accounts exceed £50,000)',
      'Grant of Representation (if deceased held mortgage in sole name)',
      'Original funeral/florist invoices (if paying funeral costs from account)',
    ],
    jointAccountProcess: 'Joint accounts are transferred to the surviving account holder.',
    soleAccountProcess: 'Sole accounts frozen. Funeral payments processed within 5 days of receiving documentation.',
    typicalTimeline: 'Online notification: response within 10 working days. Funeral payments: up to 5 days after documentation received.',
    probateThreshold: '£50,000',
    specialForms: [
      'Bereavement Instruction Form (postal notifications)',
      'Bereavement Form (telephone notifications)',
    ],
    additionalNotes: [
      'Santander Consumer Finance has a separate process: santanderconsumer.co.uk',
    ],
    slug: 'santander',
  },
  {
    name: 'TSB',
    category: 'bank',
    bereavementPhone: '0345 835 7834',
    bereavementPhoneHours: 'Mon-Fri 9am-5pm',
    bereavementEmail: 'ESUCustomerCare@tsb.co.uk',
    bereavementUrl: 'https://www.tsb.co.uk/help-and-support/bereavement-and-coping-with-loss.html',
    howToNotify: [
      'Phone: Call 0345 835 7834',
      'Email: ESUCustomerCare@tsb.co.uk',
      'Online: Complete the bereavement form and upload documents',
      'Branch: Visit any TSB branch',
      'Video call available',
    ],
    documentsRequired: [
      'Death certificate',
      'Will (if they had one)',
      'Deceased\'s account number, name, date of birth, date of death, and address',
    ],
    jointAccountProcess: 'Joint accounts transferred to surviving holder.',
    soleAccountProcess: 'Sole accounts frozen pending estate administration.',
    typicalTimeline: 'Varies depending on estate complexity.',
    specialForms: ['TSB bereavement form'],
    additionalNotes: [
      'For loans, overdrafts or credit cards: 0345 609 9283',
      'For mortgages: 0345 835 5404',
    ],
    slug: 'tsb',
  },
  {
    name: 'Metro Bank',
    category: 'bank',
    bereavementPhone: '0345 08 08 500',
    bereavementPhoneHours: 'Standard banking hours',
    bereavementEmail: 'bereavement.services@metrobank.plc.uk',
    bereavementUrl: 'https://www.metrobankonline.co.uk/ways-to-bank/i-want-some-information-about/bereavement/',
    onlineFormUrl: 'https://www.metrobankonline.co.uk/globalassets/bereavement-notification-form.pdf',
    howToNotify: [
      'Phone: Call 0345 08 08 500',
      'Email: bereavement.services@metrobank.plc.uk',
      'In-store: Visit any Metro Bank store',
      'Post: Send documents with Bereavement Notification Form',
    ],
    documentsRequired: [
      'Death certificate (original, certified copy, interim death certificate, or coroner\'s certificate)',
      'Photo ID of person dealing with estate (passport or driving licence)',
      'Completed Bereavement Notification Form (BNF)',
    ],
    jointAccountProcess: 'Joint accounts transferred to surviving holder after notification.',
    soleAccountProcess: 'Sole accounts frozen. Metro Bank locates all accounts from one notification.',
    typicalTimeline: 'Varies. Metro Bank only needs to be told once to find all related accounts.',
    specialForms: [
      'Bereavement Notification Form (BNF)',
      'Deceased Estates Indemnity Form (for balances £5,000.01 to £25,000)',
    ],
    slug: 'metro-bank',
  },
  {
    name: 'Co-operative Bank',
    category: 'bank',
    bereavementPhone: '03457 213 213',
    bereavementPhoneHours: 'Mon-Fri 8am-6pm, Sat 9am-12 noon',
    bereavementUrl: 'https://www.co-operativebank.co.uk/help-and-support/financial-support/major-life-events/bereavement/',
    onlineFormUrl: 'https://www.co-operativebank.co.uk/help-and-support/financial-support/major-life-events/bereavement/',
    howToNotify: [
      'Phone: Call 03457 213 213',
      'Online: Complete form via NIVO app or Adobe Sign',
      'Branch: Visit any Co-operative Bank branch',
      'Post: Download and post the bereavement form',
      'To stop payments urgently: Call 03457 212 212',
    ],
    documentsRequired: [
      'Death certificate (original or certified copy)',
      'Completed Bereavement Instruction Form',
    ],
    jointAccountProcess: 'Joint accounts transferred to surviving holder.',
    soleAccountProcess: 'Sole accounts frozen pending completion of Bereavement Instruction Form.',
    typicalTimeline: 'Varies. Bank contacts you to discuss next steps after notification.',
    specialForms: ['Bereavement Instruction Form (3 pages)'],
    additionalNotes: [
      'Co-op Legal Services bereavement notification service: 0333 060 7182',
      'NIVO mobile app can be used to complete and submit forms',
    ],
    slug: 'co-operative-bank',
  },
  {
    name: 'Virgin Money',
    category: 'bank',
    bereavementPhone: '0800 011 3238',
    bereavementPhoneHours: 'Mon-Fri 9am-5pm',
    bereavementUrl: 'https://uk.virginmoney.com/service/bereavement/',
    howToNotify: [
      'Phone: Call 0800 011 3238 (Bereavement Services)',
      'Online: Complete the bereavement notification form (requires death certificate)',
      'Branch: Visit any Virgin Money branch',
      'Alternative number for credit cards, mortgages, savings: 0800 012 1590 (Mon-Fri 8am-6pm, Sat 8am-3pm, Sun 10am-1pm)',
    ],
    documentsRequired: [
      'Death certificate',
      'Deceased\'s account details',
      'Photo ID of person dealing with estate',
    ],
    jointAccountProcess: 'Joint accounts transferred to surviving holder.',
    soleAccountProcess: 'Sole accounts frozen pending estate administration.',
    typicalTimeline: 'Varies depending on estate complexity.',
    additionalNotes: [
      'Covers former Clydesdale Bank and Yorkshire Bank customers',
      'Clydesdale and Yorkshire Bank customers should also call 0800 011 3238',
      'Partnership with National Bereavement Service for additional support',
    ],
    slug: 'virgin-money',
  },
  {
    name: 'Monzo',
    category: 'bank',
    bereavementPhone: '0800 802 1281',
    bereavementPhoneHours: 'Standard hours',
    internationalPhone: '+44 203 872 0620',
    bereavementEmail: 'bereavements@monzo.com',
    bereavementUrl: 'https://monzo.com/help/your-needs/SUPPORT-WHEN-A-MONZO-ACCOUNT-HOLDER-PASSES-AWAY',
    onlineFormUrl: 'https://monzo.com/bereavements',
    howToNotify: [
      'Online: Fill out the form at monzo.com/bereavements',
      'Email: bereavements@monzo.com',
      'Phone: Call 0800 802 1281',
    ],
    documentsRequired: [
      'Death certificate or interim death certificate (scan or photograph)',
      'Deceased\'s full name, date of birth, date of death, and usual address',
      'If balance over £100: completed indemnity form',
      'Non-English documents require translation',
    ],
    jointAccountProcess: 'Monzo does not currently offer traditional joint accounts. Joint accounts in Monzo work differently; contact for specifics.',
    soleAccountProcess: 'Account frozen. Anyone can report a death, but money can only be returned to executor, next of kin, or solicitor acting on their behalf.',
    typicalTimeline: 'Once all documents received, money transferred within 5 working days.',
    specialForms: ['Indemnity form (for balances over £100)'],
    additionalNotes: [
      'Digital-only bank; no branches',
      'Accepts scanned or photographed death certificates',
    ],
    slug: 'monzo',
  },
  {
    name: 'Starling Bank',
    category: 'bank',
    bereavementPhone: '020 7930 4450',
    bereavementPhoneHours: '24/7',
    bereavementUrl: 'https://www.starlingbank.com/faq/customer-support/bereavement/',
    postalAddress: 'Bereavement Team, Starling Bank Limited, 5th Floor, London Fruit and Wool Exchange, 1 Duval Square, London, E1 6PW',
    howToNotify: [
      'Email: Send documents to help@starlingbank.com addressed to Bereavement Team',
      'Phone: Call 020 7930 4450 (available 24/7)',
      'Post: Write to Bereavement Team, 1 Duval Square, London, E1 6PW',
      'Settld: Use Settld\'s free online service to notify multiple companies at once',
    ],
    documentsRequired: [
      'Death certificate or coroner\'s certificate',
      'Certified copy of passport or driving licence (not needed if you\'re a Starling customer)',
      'Grant of Probate or Letters of Administration (if balance exceeds £10,000)',
    ],
    jointAccountProcess: 'Joint account access transfers to surviving holder after documentation.',
    soleAccountProcess: 'Sole accounts frozen. Funds released only with proper documentation.',
    typicalTimeline: 'Varies depending on balance and documentation. Probate required for balances over £10,000.',
    probateThreshold: '£10,000',
    additionalNotes: [
      'Digital-only bank',
      'Existing Starling customers don\'t need to provide certified ID',
      'Partnership with Settld for streamlined notifications',
    ],
    slug: 'starling-bank',
  },
  {
    name: 'Revolut',
    category: 'bank',
    bereavementEmail: 'bereavement@revolut.com',
    bereavementUrl: 'https://help.revolut.com/help/more/legal-topics/what-happens-to-a-revolut-account-if-the-account-holder-passes-away/',
    onlineFormUrl: 'https://cdn.revolut.com/forms/Indemnity/Revolut_EN__Bereavement_Form.pdf',
    howToNotify: [
      'Email only: bereavement@revolut.com',
      'No dedicated phone line for bereavement',
    ],
    documentsRequired: [
      'Your photo ID',
      'Death certificate',
      'Grant of Probate (if applicable)',
      'Deceased\'s full legal name, date of birth, linked phone number/email',
      'Your full legal name, email address, and relationship to deceased',
    ],
    jointAccountProcess: 'Contact Revolut for specific guidance on joint/shared accounts.',
    soleAccountProcess: 'Account frozen. Specialised Bereavement team handles the case.',
    typicalTimeline: 'Varies. All communication via email only.',
    specialForms: ['Revolut Bereavement Form (PDF)'],
    additionalNotes: [
      'Digital-only bank; email-only bereavement contact',
      'No phone support for bereavement cases',
    ],
    slug: 'revolut',
  },
  {
    name: 'Chase UK',
    category: 'bank',
    bereavementPhone: '0800 376 3333',
    bereavementPhoneHours: 'Standard hours',
    internationalPhone: '+44 20 3493 0829',
    bereavementUrl: 'https://www.chase.co.uk/gb/en/hub/bereavement/',
    howToNotify: [
      'Phone: Call 0800 376 3333',
      'Death Notification Service (Chase will contact you within 10 working days)',
    ],
    documentsRequired: [
      'Death certificate (copy provided by register office)',
      'If using Death Notification Service: no separate death certificate or ID checks needed',
    ],
    jointAccountProcess: 'Contact Chase for specific guidance.',
    soleAccountProcess: 'Records updated and all communications stopped after notification.',
    typicalTimeline: 'If via Death Notification Service: Chase contacts you within 10 working days.',
    additionalNotes: [
      'Chase UK is relatively new and has a simpler bereavement process',
      'Death Notification Service saves time on ID checks and certificates',
    ],
    slug: 'chase-uk',
  },

  // ============================================================
  // BUILDING SOCIETIES
  // ============================================================
  {
    name: 'Nationwide Building Society',
    category: 'building-society',
    bereavementPhone: '0800 464 3018',
    bereavementPhoneHours: 'Mon-Fri 9am-5pm, Sat 9am-12pm',
    bereavementUrl: 'https://www.nationwide.co.uk/help/challenging-times/bereavement',
    onlineFormUrl: 'https://www.nationwide.co.uk/help/challenging-times/bereavement/tell-us',
    postalAddress: 'Bereavement Services, Specialist Customer Support, Nationwide Building Society, Swindon, SN38 3FN',
    howToNotify: [
      'Online: Complete the bereavement notification form',
      'Phone: Call 0800 464 3018',
      'Branch: Visit any Nationwide branch (appointment available)',
      'Post: Write to Bereavement Services, Swindon, SN38 3FN',
    ],
    documentsRequired: [
      'Death certificate (can be provided later if not yet available)',
      'Deceased\'s full name, address, date of birth, and date of death',
      'Notifier\'s name, address, telephone number, and relationship to deceased',
      'Personal representative\'s name and address',
    ],
    jointAccountProcess: 'Joint accounts transferred to surviving holder. Surviving member retains full access.',
    soleAccountProcess: 'Sole accounts frozen upon notification.',
    typicalTimeline: 'Varies. Nationwide will contact the personal representative with next steps.',
    additionalNotes: [
      'Anyone can notify Nationwide of a death',
      'Death certificate not required at initial notification stage',
    ],
    slug: 'nationwide',
  },
  {
    name: 'Yorkshire Building Society',
    category: 'building-society',
    bereavementPhone: '0345 1669 229',
    bereavementPhoneHours: 'Mon-Fri 9am-5pm',
    bereavementUrl: 'https://www.ybs.co.uk/help/bereavement',
    onlineFormUrl: 'https://online.ybs.co.uk/public/contact_us/bereavement.do',
    postalAddress: 'Customer Service Centre, Yorkshire Building Society, Yorkshire House, Yorkshire Drive, Bradford, BD5 8LJ',
    howToNotify: [
      'Online: Complete the bereavement notification form',
      'Phone: Call 0345 1669 229',
      'Branch: Visit any YBS branch with death certificate',
    ],
    documentsRequired: [
      'Death certificate (copy)',
      'Photo ID may be requested',
    ],
    jointAccountProcess: 'Joint accounts transferred to surviving account holder\'s name.',
    soleAccountProcess: 'Sole savings accounts frozen upon notification.',
    typicalTimeline: 'Varies. YBS contacts you with next steps after receiving death certificate.',
    specialForms: [
      'Authority to Close form (YBS1667A) for executor/administrator',
      'Declaration and Indemnity form (YBS1667)',
    ],
    slug: 'yorkshire-building-society',
  },
  {
    name: 'Coventry Building Society',
    category: 'building-society',
    bereavementPhone: '0800 587 4565',
    bereavementPhoneHours: 'Mon-Fri 8am-7pm, Sat 9am-2pm',
    bereavementUrl: 'https://www.coventrybuildingsociety.co.uk/member/help/member-support/register-a-bereavement.html',
    onlineFormUrl: 'https://www.coventrybuildingsociety.co.uk/member/help/member-support/register-a-bereavement/bereavement-form.html',
    howToNotify: [
      'Phone: Call 0800 587 4565 (specialist bereavement team)',
      'Online: Complete bereavement notification form',
      'Branch: Visit any Coventry BS branch',
      'Post: Available via bereavement page',
    ],
    documentsRequired: [
      'Date of birth, date of death, and address of deceased',
      'Basic account details (if available)',
      'Death certificate (can be provided later)',
    ],
    jointAccountProcess: 'Joint accounts transferred to surviving member.',
    soleAccountProcess: 'Sole accounts frozen pending estate resolution.',
    typicalTimeline: 'Varies. Specialist team will guide you through the process.',
    specialForms: ['Account closure form after bereavement (5 pages)'],
    slug: 'coventry-building-society',
  },
  {
    name: 'Skipton Building Society',
    category: 'building-society',
    bereavementPhone: '0345 266 1209',
    bereavementPhoneHours: 'Mon-Fri 9am-5pm',
    bereavementEmail: 'skiptondirect-bereavementnotification@skipton.co.uk',
    bereavementUrl: 'https://www.skipton.co.uk/help-and-support/extra-support/bereavement',
    onlineFormUrl: 'https://www.skipton.co.uk/bereavement/notify-us',
    howToNotify: [
      'Phone: Call 0345 266 1209 (Bereavement Team)',
      'Online: Complete the Bereavement Notification Information Request Form',
      'Email: skiptondirect-bereavementnotification@skipton.co.uk (for savings under £5,000 or mortgages)',
      'Post: Form can be posted to you on request',
    ],
    documentsRequired: [
      'Death certificate (scanned copy may be accepted for smaller balances)',
      'Security questions will be asked',
      'Proof of executor/next of kin status',
    ],
    jointAccountProcess: 'Joint accounts transferred to surviving holder.',
    soleAccountProcess: 'Sole accounts frozen. Information limited unless you can prove executor/next of kin status.',
    typicalTimeline: 'Varies depending on estate complexity and balance.',
    specialForms: [
      'Bereavement Notification Information Request Form',
      'Letter of Indemnity (for balances £1,000 or less)',
    ],
    probateThreshold: '£5,000 (for simplified email process)',
    slug: 'skipton-building-society',
  },
  {
    name: 'Leeds Building Society',
    category: 'building-society',
    bereavementPhone: '03452 682 642',
    bereavementPhoneHours: 'Mon-Fri 8am-6pm, Sat 9am-5pm',
    bereavementEmail: 'customercare@leedsbuildingsociety.co.uk',
    bereavementUrl: 'https://www.leedsbuildingsociety.co.uk/bereavement-support/',
    howToNotify: [
      'Phone: Call 03452 682 642',
      'Email: customercare@leedsbuildingsociety.co.uk with death certificate',
      'Branch: Book an appointment at a local branch',
      'Death Notification Service (free external service)',
    ],
    documentsRequired: [
      'Death certificate',
      'Account Closure Form',
      'With Will: Certified copy of Will/Probate + ID',
      'Without Will: ID for first named representative',
      'If balance over £50,000: Certified copy of Probate + ID for each executor',
    ],
    jointAccountProcess: 'Remaining holder(s) retain access. Deceased\'s name removed after death certificate received.',
    soleAccountProcess: 'Society contacts Personal Representative(s) with closure details.',
    typicalTimeline: 'Varies. ISA accounts retain tax-free status until completion, closure, or 3 years post-death.',
    probateThreshold: '£50,000',
    specialForms: ['Account Closure Form'],
    additionalNotes: [
      'Joint mortgages receive a 3-month payment hold',
      'Sole mortgages require Personal Representative contact',
      'ISA accounts keep tax-free status for up to 3 years after death',
    ],
    slug: 'leeds-building-society',
  },
  {
    name: 'Principality Building Society',
    category: 'building-society',
    bereavementPhone: '0330 333 4000',
    bereavementPhoneHours: 'Standard hours',
    bereavementEmail: 'bereavement@principality.co.uk',
    bereavementUrl: 'https://www.principality.co.uk/home/contact-us/help-and-support/supporting-you-when-someone-dies',
    postalAddress: 'Bereavement Team, Principality Buildings, PO Box 89, Queen Street, Cardiff, CF10 1UA',
    howToNotify: [
      'Phone: Call 0330 333 4000',
      'Email: bereavement@principality.co.uk',
      'Post: Write to Bereavement Team, PO Box 89, Cardiff, CF10 1UA',
      'Branch: Visit a local branch',
    ],
    documentsRequired: [
      'Death certificate (original or copy)',
      'Name of Personal Representative(s)',
    ],
    jointAccountProcess: 'Joint accounts transferred to surviving holder.',
    soleAccountProcess: 'Sole accounts frozen pending estate administration.',
    typicalTimeline: 'Varies depending on estate complexity.',
    specialForms: [
      'Bereavement Registration Form',
      'Bereavement Request to Close Account form (4 pages)',
    ],
    slug: 'principality-building-society',
  },
  {
    name: 'Nottingham Building Society',
    category: 'building-society',
    bereavementPhone: '0344 481 4444',
    bereavementPhoneHours: 'Standard hours',
    bereavementUrl: 'https://www.thenottingham.com/contact-us/bereavements',
    postalAddress: 'Nottingham Building Society, Nottingham House, 3 Fulforth Street, Nottingham, NG1 3DL',
    howToNotify: [
      'Phone: Call 0344 481 4444',
      'Branch: Visit nearest branch with death certificate',
      'Post: Send covering letter and death certificate to Nottingham House, NG1 3DL',
    ],
    documentsRequired: [
      'Death certificate (certified copy or original)',
    ],
    jointAccountProcess: 'Joint accounts transferred to surviving member.',
    soleAccountProcess: 'Sole accounts frozen pending estate resolution.',
    typicalTimeline: 'Varies.',
    slug: 'nottingham-building-society',
  },

  // ============================================================
  // ENERGY COMPANIES
  // ============================================================
  {
    name: 'British Gas',
    category: 'energy',
    bereavementPhone: '0800 294 3125',
    bereavementPhoneHours: 'Mon-Fri 9am-5pm',
    bereavementUrl: 'https://www.britishgas.co.uk/bereavement',
    onlineFormUrl: 'https://www.britishgas.co.uk/help-and-support/probate/notify',
    howToNotify: [
      'Phone: Call 0800 294 3125 (dedicated bereavement line)',
      'Online: Complete the notification form on the British Gas website',
    ],
    documentsRequired: [
      'Death certificate (if available)',
      'Account holder\'s name, address, and account number',
      'Details of who will be responsible for the property/account going forward',
    ],
    typicalTimeline: 'British Gas will contact you if they need additional information.',
    additionalNotes: [
      'Despite having a dedicated number, calls may route to general accounts queue',
      'Account can be transferred to another name or closed',
      'Final meter readings helpful to provide',
    ],
    slug: 'british-gas',
  },
  {
    name: 'EDF Energy',
    category: 'energy',
    bereavementPhone: '0808 101 4115',
    bereavementPhoneHours: 'Mon-Fri 8am-6pm, Sat 8am-2pm',
    bereavementEmail: 'hello@edfenergy.com',
    bereavementUrl: 'https://www.edfenergy.com/help-support/faq/bereavement-how-tell-us-about-death-edf-account-holder',
    onlineFormUrl: 'https://www.edfenergy.com/form/bereavement-notification-form-2022',
    howToNotify: [
      'Phone: Call 0808 101 4115 (Bereavement Support Team)',
      'Online: Complete the bereavement notification form',
      'Email: hello@edfenergy.com',
      'Post: Write to EDF at Freepost',
    ],
    documentsRequired: [
      'Deceased\'s full name, address, and date of passing',
      'Contact information for executor or administrator',
      'Death certificate (can be sent later if not available)',
    ],
    typicalTimeline: 'Varies. EDF will guide you through closing or transferring the account.',
    slug: 'edf-energy',
  },
  {
    name: 'E.ON Next',
    category: 'energy',
    bereavementPhone: '0808 501 5035',
    bereavementPhoneHours: 'Mon-Thu 9am-5pm, Fri 9am-4pm',
    bereavementEmail: 'bereavement@eonnext.com',
    bereavementUrl: 'https://www.eonnext.com/help/bereavements',
    howToNotify: [
      'Phone: Call 0808 501 5035 (E.ON Next bereavement team)',
      'Email: bereavement@eonnext.com',
      'Online: Complete the bereavement form on the website',
      'For legacy E.ON accounts: Call 0333 103 9575 or email Bereavement@e.org',
    ],
    documentsRequired: [
      'Your name and contact details',
      'Your relationship to the deceased',
      'Deceased\'s name, address, and date of death',
    ],
    typicalTimeline: 'Varies. E.ON will guide you through next steps.',
    additionalNotes: [
      'Legacy E.ON customers may need to contact the separate E.ON (E.Org) team on 0333 103 9575',
    ],
    slug: 'eon-next',
  },
  {
    name: 'OVO Energy',
    category: 'energy',
    bereavementPhone: '0330 175 9683',
    bereavementPhoneHours: 'Mon-Fri 9am-5pm',
    bereavementEmail: 'bereavement@ovoenergy.com',
    bereavementUrl: 'https://www.ovoenergy.com/help/article/bereavement',
    howToNotify: [
      'Phone: Call 0330 175 9683 (dedicated bereavement team)',
      'Email: bereavement@ovoenergy.com',
      'Online: Complete the notification form',
    ],
    documentsRequired: [
      'Your name and contact details',
      'Deceased\'s full name, postcode, or date of birth',
      'Contact details for executor or person taking over account',
      'Meter readings (if available)',
    ],
    typicalTimeline: 'Varies. OVO will assist with closing or transferring the account.',
    slug: 'ovo-energy',
  },
  {
    name: 'Octopus Energy',
    category: 'energy',
    bereavementPhone: '0808 164 1088',
    bereavementPhoneHours: 'Mon-Thu 9am-5pm, Fri 9am-4pm',
    bereavementEmail: 'hello@octopus.energy',
    bereavementUrl: 'https://octopus.energy/help-and-faqs/articles/bereavement/',
    howToNotify: [
      'Settld: Use Settld\'s free online service (Octopus\'s recommended method)',
      'Email: hello@octopus.energy',
      'Phone: Call 0808 164 1088 (general line)',
    ],
    documentsRequired: [
      'Deceased\'s name, full address, and date of passing',
      'Details of executor or administrator',
      'Meter readings and date property sold or keys returned',
    ],
    typicalTimeline: 'Varies. Accounts remain open until property transfer.',
    additionalNotes: [
      'Octopus recommends using Settld (free third-party service) to notify multiple companies at once',
      'No dedicated bereavement phone number; use general contact line',
    ],
    slug: 'octopus-energy',
  },
  {
    name: 'Scottish Power',
    category: 'energy',
    bereavementPhone: '0800 074 1986',
    bereavementPhoneHours: 'Mon-Fri 9am-5pm',
    bereavementEmail: 'contactus@scottishpower.com',
    bereavementUrl: 'https://www.scottishpower.co.uk/support-centre/bereavement',
    howToNotify: [
      'Phone: Call 0800 074 1986',
      'Email: Complete the bereavement notification form and email to contactus@scottishpower.com',
    ],
    documentsRequired: [
      'Name of person responsible for energy bills going forward',
      'Address for correspondence',
      'Death certificate (occasionally requested)',
    ],
    typicalTimeline: 'Varies. Dedicated bereavement team guides you through closing or transferring the account.',
    additionalNotes: [
      'Downloadable bereavement notification form template (Word document)',
    ],
    slug: 'scottish-power',
  },

  // ============================================================
  // TELECOMS
  // ============================================================
  {
    name: 'BT',
    category: 'telecoms',
    bereavementPhone: '0800 169 1663',
    bereavementPhoneHours: 'Mon-Fri 8am-9pm, Sat 8am-8pm, Sun varies',
    bereavementUrl: 'https://www.bt.com/help/account-and-billing/manage-account/bereavement---bt-account-holder',
    onlineFormUrl: 'https://www.bt.com/exp/help/contact-bt/form/bereavement',
    howToNotify: [
      'Phone: Call 0800 169 1663',
      'Online: Complete the bereavement contact form',
    ],
    documentsRequired: [
      'Account number or phone numbers associated with the account',
      'Email address and full address of the deceased',
      'Date of birth of the deceased',
    ],
    typicalTimeline: 'Account can be transferred to another name or closed.',
    additionalNotes: [
      'BT Pension Scheme has a separate process: btps.co.uk/ReportADeath',
    ],
    slug: 'bt',
  },
  {
    name: 'Sky',
    category: 'telecoms',
    bereavementPhone: '0333 2020 912',
    bereavementPhoneHours: 'Standard hours',
    bereavementUrl: 'https://www.sky.com/help/articles/deceased-sky-account-holder',
    howToNotify: [
      'Phone: Call 0333 2020 912',
      'Alternative: 0344 241 0333',
      'Settld: Use free Settld service to notify multiple companies',
    ],
    documentsRequired: [
      'Account holder\'s name and Sky account number',
      'Death certificate (may be requested)',
      'Deceased\'s date of birth and full address',
      'Details of new account holder (if transferring)',
    ],
    typicalTimeline: 'Sky recommends contacting at least 14 days before cancellation needs to take place.',
    additionalNotes: [
      'Account can be cancelled or transferred to another name',
      'Sky Business bereavement: separate process via sky.com/business/help',
    ],
    slug: 'sky',
  },
  {
    name: 'Virgin Media',
    category: 'telecoms',
    bereavementPhone: '0800 952 2302',
    bereavementPhoneHours: 'Mon-Fri 8am-7:45pm, Sat-Sun 9am-5:45pm',
    bereavementUrl: 'https://www.o2.co.uk/help/account/manage-your-account/bereavement',
    howToNotify: [
      'Phone: Call 0800 952 2302',
      'Online: Download and complete the Bereavement Transfer form and email it back',
    ],
    documentsRequired: [
      'Account holder\'s details',
      'Death certificate (if available)',
      'Details of new account holder (if transferring)',
    ],
    typicalTimeline: 'Accounts updated within 7 days of receiving completed form.',
    specialForms: ['Bereavement Transfer Form'],
    additionalNotes: [
      'Now part of Virgin Media O2',
      'Options: transfer service to another person or disconnect entirely',
    ],
    slug: 'virgin-media',
  },
  {
    name: 'TalkTalk',
    category: 'telecoms',
    bereavementPhone: '0345 172 0038',
    bereavementPhoneHours: 'Mon-Fri 9am-7pm, Sat 9am-6pm',
    bereavementUrl: 'https://help-centre.talktalk.co.uk/Manage_account/Change_of_circumstance/Our_bereavement_team',
    howToNotify: [
      'Phone: Call 0345 172 0038 (free from TalkTalk phone)',
    ],
    documentsRequired: [
      'Account number of the deceased',
      'Name and address of the deceased',
    ],
    typicalTimeline: 'Bereavement team assists with changing owner or closing account.',
    slug: 'talktalk',
  },

  // ============================================================
  // WATER
  // ============================================================
  {
    name: 'Thames Water',
    category: 'water',
    bereavementPhone: '0800 009 4976',
    bereavementPhoneHours: 'Mon-Fri 9am-5pm',
    bereavementUrl: 'https://www.thameswater.co.uk/help/account-and-billing/help-with-a-bereavement',
    howToNotify: [
      'Online: Complete the bereavement notification form (simplest method)',
      'Phone: Call 0800 009 4976',
    ],
    documentsRequired: [
      'Account holder\'s details',
      'Date of death',
      'Details of who will be responsible for the property going forward',
    ],
    typicalTimeline: 'Thames Water will advise on refunds or outstanding balances.',
    additionalNotes: [
      'Water companies vary by region. Other providers include:',
      'Anglian Water, Severn Trent, United Utilities, Yorkshire Water, Southern Water, South West Water, Wessex Water, Northumbrian Water, Welsh Water (Dwr Cymru)',
      'Each has its own bereavement process; contact your regional provider',
    ],
    slug: 'thames-water',
  },

  // ============================================================
  // INSURANCE & PENSIONS
  // ============================================================
  {
    name: 'Aviva',
    category: 'insurance',
    bereavementPhone: '0204 579 8999',
    bereavementPhoneHours: 'Mon-Fri standard hours',
    bereavementUrl: 'https://www.aviva.co.uk/help-and-support/contact-us/notify-us-of-a-bereavement/',
    onlineFormUrl: 'https://www.aviva.co.uk/help-and-support/contact-us/notify-us-of-a-bereavement/',
    howToNotify: [
      'Online: Fill in the bereavement notification form',
      'Phone: Call 0204 579 8999 (Life & Pensions)',
      'For pensions/savings: Call 0800 015 1142',
      'For Aviva Investors: Call 0800 051 2003',
    ],
    documentsRequired: [
      'Policy number(s)',
      'Death certificate',
      'Grant of Probate (if required)',
      'Details depend on product type',
    ],
    typicalTimeline: 'Varies by product type. Aviva will guide you through the specific process for each product held.',
    additionalNotes: [
      'Different phone numbers for different product types',
      'One online form covers all Aviva products',
    ],
    slug: 'aviva',
  },
  {
    name: 'Legal & General',
    category: 'insurance',
    bereavementPhone: '0800 137 101',
    bereavementPhoneHours: 'Standard hours',
    bereavementUrl: 'https://www.legalandgeneral.com/existing-customers/bereavement/',
    onlineFormUrl: 'https://www.legalandgeneral.com/existing-customers/bereavement/',
    postalAddress: 'Customer Services, Legal & General Home Finance, PO BOX 17225, Solihull, B91 1US',
    howToNotify: [
      'Phone: Call 0800 137 101 (life insurance claims)',
      'Online: Complete the secure bereavement form',
      'Post: Write to PO Box 17225, Solihull, B91 1US',
      'For lifetime mortgages: Call 03330 048 444 (Mon-Fri 8:30am-5pm)',
    ],
    documentsRequired: [
      'Death certificate (may be verified over the phone)',
      'Name, address, and date of birth of the deceased',
      'Policy number (if known)',
    ],
    typicalTimeline: 'Varies by product type.',
    additionalNotes: [
      'ReAssure (now part of L&G) has a separate notification form: reassure.co.uk/notify/',
    ],
    slug: 'legal-and-general',
  },
  {
    name: 'Royal London',
    category: 'insurance',
    bereavementPhone: '0345 602 1885',
    bereavementPhoneHours: 'Standard hours',
    bereavementUrl: 'https://www.royallondon.com/existing-customers/help-and-support/make-a-claim/tell-us-about-a-bereavement/',
    postalAddress: 'PO Box 409, Royal London House, Alderley Park, Congleton Road, Nether Alderley, Macclesfield, SK10 4EL',
    howToNotify: [
      'Online: Use the bereavement notification page (process varies by policy type)',
      'Phone: Call 0345 602 1885',
      'Post: Write to PO Box 409, Macclesfield, SK10 4EL',
    ],
    documentsRequired: [
      'Name of the deceased',
      'Last known address',
      'Policy type and number (if known)',
      'Death certificate',
    ],
    typicalTimeline: 'Varies by policy type.',
    additionalNotes: [
      'Alternative postal address for some policies: PO Box 698, SK10 9AN',
      'Process depends on policy type; website guides you through the right steps',
    ],
    slug: 'royal-london',
  },
  {
    name: 'Standard Life',
    category: 'insurance',
    bereavementPhone: '0345 279 1001',
    bereavementPhoneHours: 'Standard hours',
    bereavementEmail: 'sipp_bereavements@standardlife.com',
    bereavementUrl: 'https://www.standardlife.co.uk/help/bereavement',
    onlineFormUrl: 'https://www.standardlife.co.uk/help/bereavement/bereavement-form',
    howToNotify: [
      'Online: Complete the bereavement form (information goes to Bereavements Team)',
      'Phone: Call 0345 279 1001',
      'Email: sipp_bereavements@standardlife.com (for SIPP/Wrap products)',
      'For Standard Life Home Finance: Call 0800 188 4815 or email LMBereavements@standardlife.com',
    ],
    documentsRequired: [
      'Death certificate',
      'Policy/plan details',
      'Details of deceased and person reporting',
    ],
    typicalTimeline: 'Specialist in Bereavements Team will contact you within 2 weeks of submission.',
    additionalNotes: [
      'Now part of abrdn (Aberdeen)',
      'Different contact routes for different product types',
    ],
    slug: 'standard-life',
  },
  {
    name: 'Prudential',
    category: 'insurance',
    // bereavementPhone removed: 0800 000 000 is a placeholder, not a verified number
    bereavementPhoneHours: 'Mon-Fri 8am-6pm',
    bereavementUrl: 'https://www.mandg.com/pru/customer/en-gb/existing-customers/bereavement-support/notify-us-of-a-death',
    onlineFormUrl: 'https://mypru.pru.co.uk/onlinebereavement/deceased',
    postalAddress: 'Prudential, Lancing, BN15 8GB',
    howToNotify: [
      'Online: Use the online notification tool (quickest method)',
      'Phone: Call and say "Notify you of a death" when prompted',
      'Post: Write to Prudential, Lancing, BN15 8GB',
    ],
    documentsRequired: [
      'Details of all products/plans the deceased held with Prudential',
      'Death certificate',
      'Policy numbers (if known)',
    ],
    typicalTimeline: 'Varies by product type. Prudential will guide you through next steps.',
    additionalNotes: [
      'Now part of M&G',
      'Phone uses speech recognition; say "Notify you of a death"',
      'One notification covers all Prudential products',
    ],
    slug: 'prudential',
  },

  // ============================================================
  // GOVERNMENT
  // ============================================================
  {
    name: 'Tell Us Once (DWP/Government)',
    category: 'government',
    bereavementPhone: '0800 085 7308',
    bereavementPhoneHours: 'Available after registering the death',
    bereavementUrl: 'https://www.gov.uk/after-a-death/report-without-tell-us-once',
    howToNotify: [
      'Tell Us Once: Use the unique reference number given by the registrar when you register the death',
      'Online: Complete via GOV.UK within 28 days of getting reference number',
      'Phone: Call 0800 085 7308',
      'Must be used within 28 days of receiving reference number',
    ],
    documentsRequired: [
      'Tell Us Once reference number (from registrar)',
      'National Insurance number of the deceased',
      'Date of birth and date of death',
      'Details of benefits/services the deceased received',
    ],
    typicalTimeline: 'Immediate notification to all participating government departments.',
    additionalNotes: [
      'One notification covers: HMRC, DWP, Passport Office, DVLA, council tax, electoral roll, and more',
      'Available in most local authority areas',
      'Not available in Northern Ireland',
      'Does not cover: banks, utilities, insurance, or private companies',
    ],
    slug: 'tell-us-once',
  },
  {
    name: 'HMRC',
    category: 'government',
    bereavementPhone: '0300 322 9620',
    bereavementPhoneHours: 'Mon-Fri 8am-6pm (less busy before 10am)',
    internationalPhone: '+44 300 322 9620',
    bereavementUrl: 'https://www.gov.uk/find-hmrc-contacts/bereavement-and-deceased-estate-enquiries',
    howToNotify: [
      'Tell Us Once: Preferred method (covers PAYE, self-assessment, child benefit)',
      'Phone: Call 0300 322 9620 (Bereavement Helpline)',
      'Form P1000: Fill in if you cannot call the helpline',
      'Note: Contact separately for business taxes like VAT',
    ],
    documentsRequired: [
      'National Insurance number of the deceased',
      'Date of death',
      'Details of who is dealing with the estate',
      'Form P1000 (if unable to call)',
    ],
    typicalTimeline: 'HMRC will process tax affairs and issue any refunds due to the estate.',
    specialForms: ['Form P1000 (alternative to phone notification)'],
    additionalNotes: [
      'Phone uses speech recognition; say why you are calling',
      'Tell Us Once does NOT cover business taxes (VAT, Corporation Tax)',
      'Self Assessment returns may still need to be filed for the tax year of death',
    ],
    slug: 'hmrc',
  },
  {
    name: 'DWP (Department for Work and Pensions)',
    category: 'government',
    bereavementPhone: '0800 151 2012',
    bereavementPhoneHours: 'Mon-Fri 8am-6pm',
    bereavementUrl: 'https://www.gov.uk/after-a-death/report-without-tell-us-once',
    howToNotify: [
      'Tell Us Once: Preferred method (notifies DWP automatically)',
      'Phone: Call 0800 151 2012 (Bereavement Service)',
      'Welsh language: 0800 731 0453',
      'Relay UK: 18001 0800 151 2012',
      'Textphone: 0800 731 0464',
    ],
    documentsRequired: [
      'National Insurance number of the deceased',
      'Date of death',
      'Details of any benefits the deceased was receiving',
    ],
    typicalTimeline: 'Benefits will be stopped. Any overpayments may need to be repaid from the estate. Bereavement benefits may be claimable by the surviving spouse/civil partner.',
    additionalNotes: [
      'DWP runs the Tell Us Once service on behalf of most government departments',
      'Bereavement Support Payment may be available to surviving spouse/civil partner',
      'Funeral Expenses Payment may be available for those on certain benefits',
    ],
    slug: 'dwp',
  },
  {
    name: 'DVLA',
    category: 'government',
    bereavementPhone: '0300 790 6802',
    bereavementPhoneHours: 'Standard hours',
    bereavementUrl: 'https://www.gov.uk/tell-dvla-about-bereavement',
    postalAddress: 'DVLA, Swansea, SA99 1AB',
    howToNotify: [
      'Tell Us Once: Covers DVLA notification if available in your area',
      'Post: Write to DVLA, Swansea, SA99 1AB with the driving licence and a covering letter',
      'Phone: Call 0300 790 6802 for guidance',
    ],
    documentsRequired: [
      'Driving licence of the deceased (if available)',
      'Covering letter stating: your relationship, date of death, deceased\'s full name and address',
      'Death certificate is NOT required by DVLA',
    ],
    typicalTimeline: 'DVLA processes notifications within 4 weeks.',
    additionalNotes: [
      'Also need to notify about any vehicles registered to the deceased',
      'Vehicle tax (road tax) will be cancelled and refunded',
      'V5C (log book) needs to be updated if vehicle is being kept',
      'SORN the vehicle if it will not be driven or taxed',
    ],
    slug: 'dvla',
  },
  {
    name: 'HM Passport Office',
    category: 'government',
    bereavementPhone: '0300 222 0000',
    bereavementPhoneHours: 'Standard hours',
    bereavementUrl: 'https://www.gov.uk/government/publications/what-to-do-with-a-passport-when-the-passport-holder-has-died',
    howToNotify: [
      'Tell Us Once: Covers passport cancellation if available in your area',
      'Phone: Call 0300 222 0000 (HM Passport Office helpline)',
      'Post: Return passport to HM Passport Office',
      'If abroad: Contact the Foreign, Commonwealth & Development Office',
    ],
    documentsRequired: [
      'Passport of the deceased (cut corners off before sending to prevent misuse)',
      'Covering letter with deceased\'s details',
    ],
    typicalTimeline: 'Passport is officially cancelled and securely destroyed by HMPO.',
    additionalNotes: [
      'Tell Us Once is the preferred method and eliminates need to post the passport',
      'Cut off passport corners before posting as a security measure',
      'Passport should be returned promptly to prevent identity fraud risk',
    ],
    slug: 'passport-office',
  },
  {
    name: 'Council Tax',
    category: 'government',
    bereavementUrl: 'https://www.gov.uk/after-a-death',
    howToNotify: [
      'Tell Us Once: Covers council tax notification in most areas',
      'Direct: Contact your local council\'s council tax department',
      'Notify within a month if possible',
    ],
    documentsRequired: [
      'Date of death',
      'Property address',
      'Details of any remaining occupants',
    ],
    typicalTimeline: 'Exemptions and discounts applied from date of death. Class F exemption lasts until 6 months after probate is granted.',
    additionalNotes: [
      'Class F exemption: Property left empty after death is exempt from council tax until 6 months after probate granted',
      'Single person discount: If one adult remains, 25% discount applies from date of death',
      'Rented properties: Exempt from date of death until tenancy ends',
      'Executor not personally liable; council tax paid from estate',
      'Contact your specific local council for their process',
    ],
    slug: 'council-tax',
  },
]

// Helper function to get contacts by category
export function getContactsByCategory(category: BereavementContact['category']): BereavementContact[] {
  return bereavementContacts.filter(c => c.category === category)
}

// Helper function to get a contact by slug
export function getContactBySlug(slug: string): BereavementContact | undefined {
  return bereavementContacts.find(c => c.slug === slug)
}

// Helper to get all slugs for static generation
export function getAllContactSlugs(): string[] {
  return bereavementContacts.map(c => c.slug)
}

// Category labels for display
export const categoryLabels: Record<BereavementContact['category'], string> = {
  bank: 'Banks',
  'building-society': 'Building Societies',
  energy: 'Energy Companies',
  telecoms: 'Telecoms & Broadband',
  water: 'Water Companies',
  insurance: 'Insurance & Pensions',
  government: 'Government',
}

// Category order for display
export const categoryOrder: BereavementContact['category'][] = [
  'government',
  'bank',
  'building-society',
  'insurance',
  'energy',
  'telecoms',
  'water',
]
