export interface CityData {
  slug: string;
  name: string;
  region: string;
  nation: 'England' | 'Wales' | 'Scotland' | 'Northern Ireland';
  registrarName: string;
  registrarAddress: string;
  registrarPhone: string;
  registrarUrl: string;
  councilName: string;
  councilPhone: string;
  councilUrl: string;
  registrationDeadlineDays: number; // 5 for England/Wales, 8 for Scotland, 5 for NI
  hasCoroner: boolean; // England/Wales/NI have coroners, Scotland has Procurator Fiscal
  hasTellUsOnce: boolean; // Not available in NI
  probateTerm: string; // 'Probate' or 'Confirmation' (Scotland)
  localNotes?: string;
}

export const cities: CityData[] = [
  // London Boroughs
  {
    slug: 'london-westminster',
    name: 'Westminster',
    region: 'London',
    nation: 'England',
    registrarName: 'Westminster Register Office',
    registrarAddress: 'Westminster City Hall, 64 Victoria Street, London SW1E 6QP',
    registrarPhone: '020 7641 7500',
    registrarUrl: 'https://www.westminster.gov.uk/births-deaths-and-ceremonies',
    councilName: 'Westminster City Council',
    councilPhone: '020 7641 6000',
    councilUrl: 'https://www.westminster.gov.uk',
    registrationDeadlineDays: 5,
    hasCoroner: true,
    hasTellUsOnce: true,
    probateTerm: 'Probate',
    localNotes: 'Westminster handles a high number of registrations due to the many hospitals in central London, including St Thomas\' and Chelsea and Westminster.',
  },
  {
    slug: 'london-camden',
    name: 'Camden',
    region: 'London',
    nation: 'England',
    registrarName: 'Camden Register Office',
    registrarAddress: 'Camden Town Hall, Judd Street, London WC1H 9JE',
    registrarPhone: '020 7974 1892',
    registrarUrl: 'https://www.camden.gov.uk/register-a-death',
    councilName: 'London Borough of Camden',
    councilPhone: '020 7974 4444',
    councilUrl: 'https://www.camden.gov.uk',
    registrationDeadlineDays: 5,
    hasCoroner: true,
    hasTellUsOnce: true,
    probateTerm: 'Probate',
    localNotes: 'Camden\'s register office is within Camden Town Hall near King\'s Cross. University College Hospital and the Royal Free Hospital are both in the borough.',
  },
  {
    slug: 'london-tower-hamlets',
    name: 'Tower Hamlets',
    region: 'London',
    nation: 'England',
    registrarName: 'Tower Hamlets Register Office',
    registrarAddress: 'Mulberry Place, 5 Clove Crescent, London E14 2BG',
    registrarPhone: '020 7364 1426',
    registrarUrl: 'https://www.towerhamlets.gov.uk/lgnl/births_deaths_and_marriages',
    councilName: 'London Borough of Tower Hamlets',
    councilPhone: '020 7364 5000',
    councilUrl: 'https://www.towerhamlets.gov.uk',
    registrationDeadlineDays: 5,
    hasCoroner: true,
    hasTellUsOnce: true,
    probateTerm: 'Probate',
    localNotes: 'Tower Hamlets has a large Bangladeshi community. The council can provide interpreting services if needed, and local mosques offer support for Islamic funeral arrangements.',
  },
  {
    slug: 'london-southwark',
    name: 'Southwark',
    region: 'London',
    nation: 'England',
    registrarName: 'Southwark Register Office',
    registrarAddress: '34 Peckham Road, London SE5 8QA',
    registrarPhone: '020 7525 7237',
    registrarUrl: 'https://www.southwark.gov.uk/births-deaths-and-ceremonies',
    councilName: 'London Borough of Southwark',
    councilPhone: '020 7525 5000',
    councilUrl: 'https://www.southwark.gov.uk',
    registrationDeadlineDays: 5,
    hasCoroner: true,
    hasTellUsOnce: true,
    probateTerm: 'Probate',
    localNotes: 'King\'s College Hospital and Guy\'s Hospital are both in Southwark, so many deaths in south-east London are registered here.',
  },
  {
    slug: 'london-hackney',
    name: 'Hackney',
    region: 'London',
    nation: 'England',
    registrarName: 'Hackney Register Office',
    registrarAddress: 'Hackney Service Centre, 1 Hillman Street, London E8 1DY',
    registrarPhone: '020 8356 3316',
    registrarUrl: 'https://hackney.gov.uk/registrars',
    councilName: 'London Borough of Hackney',
    councilPhone: '020 8356 5000',
    councilUrl: 'https://hackney.gov.uk',
    registrationDeadlineDays: 5,
    hasCoroner: true,
    hasTellUsOnce: true,
    probateTerm: 'Probate',
    localNotes: 'Hackney has a diverse community including a significant Orthodox Jewish population. Local synagogues and the United Synagogue burial society can assist with traditional Jewish funeral arrangements.',
  },
  {
    slug: 'london-lambeth',
    name: 'Lambeth',
    region: 'London',
    nation: 'England',
    registrarName: 'Lambeth Register Office',
    registrarAddress: 'Lambeth Town Hall, Brixton Hill, London SW2 1RW',
    registrarPhone: '020 7926 9420',
    registrarUrl: 'https://www.lambeth.gov.uk/births-deaths-marriages',
    councilName: 'London Borough of Lambeth',
    councilPhone: '020 7926 1000',
    councilUrl: 'https://www.lambeth.gov.uk',
    registrationDeadlineDays: 5,
    hasCoroner: true,
    hasTellUsOnce: true,
    probateTerm: 'Probate',
  },
  {
    slug: 'london-islington',
    name: 'Islington',
    region: 'London',
    nation: 'England',
    registrarName: 'Islington Register Office',
    registrarAddress: 'Islington Town Hall, Upper Street, London N1 2UD',
    registrarPhone: '020 7527 6350',
    registrarUrl: 'https://www.islington.gov.uk/births-deaths-and-marriages',
    councilName: 'London Borough of Islington',
    councilPhone: '020 7527 2000',
    councilUrl: 'https://www.islington.gov.uk',
    registrationDeadlineDays: 5,
    hasCoroner: true,
    hasTellUsOnce: true,
    probateTerm: 'Probate',
  },
  {
    slug: 'london-greenwich',
    name: 'Greenwich',
    region: 'London',
    nation: 'England',
    registrarName: 'Greenwich Register Office',
    registrarAddress: 'The Woolwich Centre, 35 Wellington Street, London SE18 6HQ',
    registrarPhone: '020 8921 5130',
    registrarUrl: 'https://www.royalgreenwich.gov.uk/births-deaths-marriages',
    councilName: 'Royal Borough of Greenwich',
    councilPhone: '020 8854 8888',
    councilUrl: 'https://www.royalgreenwich.gov.uk',
    registrationDeadlineDays: 5,
    hasCoroner: true,
    hasTellUsOnce: true,
    probateTerm: 'Probate',
    localNotes: 'Queen Elizabeth Hospital is the main hospital in the borough. Greenwich has several historic cemeteries and crematoria including Eltham Crematorium.',
  },
  {
    slug: 'london-wandsworth',
    name: 'Wandsworth',
    region: 'London',
    nation: 'England',
    registrarName: 'Wandsworth Register Office',
    registrarAddress: 'Wandsworth Town Hall, Wandsworth High Street, London SW18 2PU',
    registrarPhone: '020 8871 6120',
    registrarUrl: 'https://www.wandsworth.gov.uk/births-deaths-and-marriages',
    councilName: 'London Borough of Wandsworth',
    councilPhone: '020 8871 6000',
    councilUrl: 'https://www.wandsworth.gov.uk',
    registrationDeadlineDays: 5,
    hasCoroner: true,
    hasTellUsOnce: true,
    probateTerm: 'Probate',
    localNotes: 'St George\'s Hospital in Tooting is one of the largest hospitals in south-west London. Putney Vale Cemetery and Crematorium serves the area.',
  },
  {
    slug: 'london-croydon',
    name: 'Croydon',
    region: 'London',
    nation: 'England',
    registrarName: 'Croydon Register Office',
    registrarAddress: 'Croydon Clocktower, Katharine Street, Croydon CR9 1ET',
    registrarPhone: '020 8760 5785',
    registrarUrl: 'https://www.croydon.gov.uk/births-deaths-marriages',
    councilName: 'London Borough of Croydon',
    councilPhone: '020 8726 6000',
    councilUrl: 'https://www.croydon.gov.uk',
    registrationDeadlineDays: 5,
    hasCoroner: true,
    hasTellUsOnce: true,
    probateTerm: 'Probate',
    localNotes: 'Croydon University Hospital is the main hospital. Croydon Crematorium and several local cemeteries serve the borough.',
  },

  // Major English Cities
  {
    slug: 'manchester',
    name: 'Manchester',
    region: 'North West England',
    nation: 'England',
    registrarName: 'Manchester Register Office',
    registrarAddress: 'Heron House, 47 Lloyd Street, Manchester M2 5LE',
    registrarPhone: '0161 234 7900',
    registrarUrl: 'https://www.manchester.gov.uk/info/200088/register_office',
    councilName: 'Manchester City Council',
    councilPhone: '0161 234 5000',
    councilUrl: 'https://www.manchester.gov.uk',
    registrationDeadlineDays: 5,
    hasCoroner: true,
    hasTellUsOnce: true,
    probateTerm: 'Probate',
    localNotes: 'Manchester has several large hospitals including Manchester Royal Infirmary and Wythenshawe Hospital. The city has diverse communities with dedicated funeral services for Muslim, Hindu, Sikh, and Jewish families.',
  },
  {
    slug: 'birmingham',
    name: 'Birmingham',
    region: 'West Midlands',
    nation: 'England',
    registrarName: 'Birmingham Register Office',
    registrarAddress: 'Holliday Street, Birmingham B1 1TJ',
    registrarPhone: '0121 675 1038',
    registrarUrl: 'https://www.birmingham.gov.uk/births-deaths-marriages',
    councilName: 'Birmingham City Council',
    councilPhone: '0121 303 1111',
    councilUrl: 'https://www.birmingham.gov.uk',
    registrationDeadlineDays: 5,
    hasCoroner: true,
    hasTellUsOnce: true,
    probateTerm: 'Probate',
    localNotes: 'Birmingham is the UK\'s second largest city with a diverse population. Queen Elizabeth Hospital Birmingham and City Hospital are major hospitals. The city has dedicated Islamic, Hindu, and Sikh funeral services.',
  },
  {
    slug: 'leeds',
    name: 'Leeds',
    region: 'Yorkshire and the Humber',
    nation: 'England',
    registrarName: 'Leeds Register Office',
    registrarAddress: 'Belgrave House, Belgrave Street, Leeds LS2 8DQ',
    registrarPhone: '0113 222 4408',
    registrarUrl: 'https://www.leeds.gov.uk/births-deaths-and-marriages',
    councilName: 'Leeds City Council',
    councilPhone: '0113 222 4444',
    councilUrl: 'https://www.leeds.gov.uk',
    registrationDeadlineDays: 5,
    hasCoroner: true,
    hasTellUsOnce: true,
    probateTerm: 'Probate',
    localNotes: 'Leeds General Infirmary and St James\'s University Hospital (Jimmy\'s) are the main hospitals. Lawnswood Crematorium and Cottingley Hall Crematorium serve the city.',
  },
  {
    slug: 'liverpool',
    name: 'Liverpool',
    region: 'North West England',
    nation: 'England',
    registrarName: 'Liverpool Register Office',
    registrarAddress: 'St George\'s Hall, Lime Street, Liverpool L1 1JJ',
    registrarPhone: '0151 233 3004',
    registrarUrl: 'https://www.liverpool.gov.uk/births-deaths-and-marriages',
    councilName: 'Liverpool City Council',
    councilPhone: '0151 233 3000',
    councilUrl: 'https://www.liverpool.gov.uk',
    registrationDeadlineDays: 5,
    hasCoroner: true,
    hasTellUsOnce: true,
    probateTerm: 'Probate',
    localNotes: 'The Royal Liverpool University Hospital and Aintree University Hospital are the city\'s main hospitals. Anfield Crematorium and Springwood Crematorium serve the area.',
  },
  {
    slug: 'sheffield',
    name: 'Sheffield',
    region: 'Yorkshire and the Humber',
    nation: 'England',
    registrarName: 'Sheffield Register Office',
    registrarAddress: 'Surrey Street, Sheffield S1 2LH',
    registrarPhone: '0114 273 4567',
    registrarUrl: 'https://www.sheffield.gov.uk/births-deaths-marriages',
    councilName: 'Sheffield City Council',
    councilPhone: '0114 273 4567',
    councilUrl: 'https://www.sheffield.gov.uk',
    registrationDeadlineDays: 5,
    hasCoroner: true,
    hasTellUsOnce: true,
    probateTerm: 'Probate',
    localNotes: 'Sheffield has two main hospitals: the Northern General Hospital and the Royal Hallamshire Hospital. City Road Cemetery and Hutcliffe Wood Crematorium serve the area.',
  },
  {
    slug: 'bristol',
    name: 'Bristol',
    region: 'South West England',
    nation: 'England',
    registrarName: 'Bristol Register Office',
    registrarAddress: 'City Hall, College Green, Bristol BS1 5TR',
    registrarPhone: '0117 922 2800',
    registrarUrl: 'https://www.bristol.gov.uk/births-deaths-marriages',
    councilName: 'Bristol City Council',
    councilPhone: '0117 922 2000',
    councilUrl: 'https://www.bristol.gov.uk',
    registrationDeadlineDays: 5,
    hasCoroner: true,
    hasTellUsOnce: true,
    probateTerm: 'Probate',
    localNotes: 'Bristol Royal Infirmary and Southmead Hospital are the main hospitals. South Bristol Crematorium and Canford Crematorium serve the area.',
  },
  {
    slug: 'newcastle',
    name: 'Newcastle upon Tyne',
    region: 'North East England',
    nation: 'England',
    registrarName: 'Newcastle Register Office',
    registrarAddress: 'Newcastle Civic Centre, Barras Bridge, Newcastle upon Tyne NE1 8QH',
    registrarPhone: '0191 211 6516',
    registrarUrl: 'https://www.newcastle.gov.uk/births-deaths-marriages',
    councilName: 'Newcastle City Council',
    councilPhone: '0191 278 7878',
    councilUrl: 'https://www.newcastle.gov.uk',
    registrationDeadlineDays: 5,
    hasCoroner: true,
    hasTellUsOnce: true,
    probateTerm: 'Probate',
    localNotes: 'The Royal Victoria Infirmary (RVI) and Freeman Hospital are Newcastle\'s major hospitals. The West Road Crematorium is the city\'s main crematorium.',
  },
  {
    slug: 'nottingham',
    name: 'Nottingham',
    region: 'East Midlands',
    nation: 'England',
    registrarName: 'Nottingham Register Office',
    registrarAddress: 'The Council House, Old Market Square, Nottingham NG1 2DT',
    registrarPhone: '0115 876 3600',
    registrarUrl: 'https://www.nottinghamcity.gov.uk/births-deaths-marriages',
    councilName: 'Nottingham City Council',
    councilPhone: '0115 915 5555',
    councilUrl: 'https://www.nottinghamcity.gov.uk',
    registrationDeadlineDays: 5,
    hasCoroner: true,
    hasTellUsOnce: true,
    probateTerm: 'Probate',
    localNotes: 'Nottingham University Hospitals includes the Queen\'s Medical Centre and Nottingham City Hospital. Bramcote Crematorium and Wilford Hill Crematorium serve the city.',
  },
  {
    slug: 'leicester',
    name: 'Leicester',
    region: 'East Midlands',
    nation: 'England',
    registrarName: 'Leicester Register Office',
    registrarAddress: 'Town Hall Square, Leicester LE1 9BG',
    registrarPhone: '0116 454 1005',
    registrarUrl: 'https://www.leicester.gov.uk/births-deaths-marriages',
    councilName: 'Leicester City Council',
    councilPhone: '0116 454 1000',
    councilUrl: 'https://www.leicester.gov.uk',
    registrationDeadlineDays: 5,
    hasCoroner: true,
    hasTellUsOnce: true,
    probateTerm: 'Probate',
    localNotes: 'Leicester Royal Infirmary is the main hospital. Leicester has one of the largest Hindu and Sikh communities in the UK, with well-established funeral services for these faiths. Gilroes Cemetery and Crematorium is the city\'s main facility.',
  },
  {
    slug: 'coventry',
    name: 'Coventry',
    region: 'West Midlands',
    nation: 'England',
    registrarName: 'Coventry Register Office',
    registrarAddress: 'Cheylesmore Manor House, Manor House Drive, Coventry CV1 2ND',
    registrarPhone: '024 7683 3132',
    registrarUrl: 'https://www.coventry.gov.uk/births-deaths-marriages',
    councilName: 'Coventry City Council',
    councilPhone: '024 7683 3333',
    councilUrl: 'https://www.coventry.gov.uk',
    registrationDeadlineDays: 5,
    hasCoroner: true,
    hasTellUsOnce: true,
    probateTerm: 'Probate',
    localNotes: 'University Hospitals Coventry and Warwickshire is the main hospital. Canley Garden Cemetery and Crematorium serves the area.',
  },
  {
    slug: 'bradford',
    name: 'Bradford',
    region: 'Yorkshire and the Humber',
    nation: 'England',
    registrarName: 'Bradford Register Office',
    registrarAddress: 'City Hall, Centenary Square, Bradford BD1 1HY',
    registrarPhone: '01274 432151',
    registrarUrl: 'https://www.bradford.gov.uk/births-deaths-marriages',
    councilName: 'City of Bradford Metropolitan District Council',
    councilPhone: '01274 432111',
    councilUrl: 'https://www.bradford.gov.uk',
    registrationDeadlineDays: 5,
    hasCoroner: true,
    hasTellUsOnce: true,
    probateTerm: 'Probate',
    localNotes: 'Bradford Royal Infirmary is the main hospital. Bradford has a large South Asian community with well-established Islamic funeral services. Scholemoor Cemetery and Crematorium is the main facility.',
  },
  {
    slug: 'sunderland',
    name: 'Sunderland',
    region: 'North East England',
    nation: 'England',
    registrarName: 'Sunderland Register Office',
    registrarAddress: 'Sunderland Civic Centre, Burdon Road, Sunderland SR2 7DN',
    registrarPhone: '0191 520 5552',
    registrarUrl: 'https://www.sunderland.gov.uk/births-deaths-marriages',
    councilName: 'Sunderland City Council',
    councilPhone: '0191 520 5555',
    councilUrl: 'https://www.sunderland.gov.uk',
    registrationDeadlineDays: 5,
    hasCoroner: true,
    hasTellUsOnce: true,
    probateTerm: 'Probate',
    localNotes: 'Sunderland Royal Hospital is the main hospital. Sunderland Crematorium at Chester Road serves the area.',
  },
  {
    slug: 'plymouth',
    name: 'Plymouth',
    region: 'South West England',
    nation: 'England',
    registrarName: 'Plymouth Register Office',
    registrarAddress: 'Council House, Armada Way, Plymouth PL1 2AA',
    registrarPhone: '01752 307400',
    registrarUrl: 'https://www.plymouth.gov.uk/births-deaths-marriages',
    councilName: 'Plymouth City Council',
    councilPhone: '01752 668000',
    councilUrl: 'https://www.plymouth.gov.uk',
    registrationDeadlineDays: 5,
    hasCoroner: true,
    hasTellUsOnce: true,
    probateTerm: 'Probate',
    localNotes: 'Derriford Hospital is the main hospital serving Plymouth and much of Devon and Cornwall. Weston Mill Crematorium and Efford Cemetery serve the city.',
  },
  {
    slug: 'stoke-on-trent',
    name: 'Stoke-on-Trent',
    region: 'West Midlands',
    nation: 'England',
    registrarName: 'Stoke-on-Trent Register Office',
    registrarAddress: 'Civic Centre, Glebe Street, Stoke-on-Trent ST4 1HH',
    registrarPhone: '01782 234567',
    registrarUrl: 'https://www.stoke.gov.uk/births-deaths-marriages',
    councilName: 'Stoke-on-Trent City Council',
    councilPhone: '01782 234567',
    councilUrl: 'https://www.stoke.gov.uk',
    registrationDeadlineDays: 5,
    hasCoroner: true,
    hasTellUsOnce: true,
    probateTerm: 'Probate',
    localNotes: 'Royal Stoke University Hospital is the main hospital. Carmountside Crematorium is the city\'s main crematorium.',
  },
  {
    slug: 'wolverhampton',
    name: 'Wolverhampton',
    region: 'West Midlands',
    nation: 'England',
    registrarName: 'Wolverhampton Register Office',
    registrarAddress: 'Civic Centre, St Peter\'s Square, Wolverhampton WV1 1SH',
    registrarPhone: '01902 554242',
    registrarUrl: 'https://www.wolverhampton.gov.uk/births-deaths-marriages',
    councilName: 'City of Wolverhampton Council',
    councilPhone: '01902 551155',
    councilUrl: 'https://www.wolverhampton.gov.uk',
    registrationDeadlineDays: 5,
    hasCoroner: true,
    hasTellUsOnce: true,
    probateTerm: 'Probate',
    localNotes: 'New Cross Hospital is the main hospital. Bushbury Crematorium serves the area.',
  },
  {
    slug: 'southampton',
    name: 'Southampton',
    region: 'South East England',
    nation: 'England',
    registrarName: 'Southampton Register Office',
    registrarAddress: 'Bugle House, Bugle Street, Southampton SO14 2AJ',
    registrarPhone: '023 8083 3009',
    registrarUrl: 'https://www.southampton.gov.uk/births-deaths-marriages',
    councilName: 'Southampton City Council',
    councilPhone: '023 8083 3000',
    councilUrl: 'https://www.southampton.gov.uk',
    registrationDeadlineDays: 5,
    hasCoroner: true,
    hasTellUsOnce: true,
    probateTerm: 'Probate',
    localNotes: 'Southampton General Hospital is the main hospital. Southampton Crematorium at East Road serves the area.',
  },
  {
    slug: 'portsmouth',
    name: 'Portsmouth',
    region: 'South East England',
    nation: 'England',
    registrarName: 'Portsmouth Register Office',
    registrarAddress: 'Milldam House, Burnaby Road, Portsmouth PO1 3AF',
    registrarPhone: '023 9268 8632',
    registrarUrl: 'https://www.portsmouth.gov.uk/births-deaths-marriages',
    councilName: 'Portsmouth City Council',
    councilPhone: '023 9282 2251',
    councilUrl: 'https://www.portsmouth.gov.uk',
    registrationDeadlineDays: 5,
    hasCoroner: true,
    hasTellUsOnce: true,
    probateTerm: 'Probate',
    localNotes: 'Queen Alexandra Hospital is the main hospital. Portchester Crematorium serves the area.',
  },
  {
    slug: 'reading',
    name: 'Reading',
    region: 'South East England',
    nation: 'England',
    registrarName: 'Reading Register Office',
    registrarAddress: 'Yeomanry House, 131 Castle Hill, Reading RG1 7TA',
    registrarPhone: '0118 937 3304',
    registrarUrl: 'https://www.reading.gov.uk/births-deaths-marriages',
    councilName: 'Reading Borough Council',
    councilPhone: '0118 937 3787',
    councilUrl: 'https://www.reading.gov.uk',
    registrationDeadlineDays: 5,
    hasCoroner: true,
    hasTellUsOnce: true,
    probateTerm: 'Probate',
    localNotes: 'Royal Berkshire Hospital is the main hospital. Reading Crematorium at All Hallows Road serves the area.',
  },
  {
    slug: 'derby',
    name: 'Derby',
    region: 'East Midlands',
    nation: 'England',
    registrarName: 'Derby Register Office',
    registrarAddress: 'Council House, Corporation Street, Derby DE1 2FS',
    registrarPhone: '01332 641672',
    registrarUrl: 'https://www.derby.gov.uk/births-deaths-marriages',
    councilName: 'Derby City Council',
    councilPhone: '01332 293111',
    councilUrl: 'https://www.derby.gov.uk',
    registrationDeadlineDays: 5,
    hasCoroner: true,
    hasTellUsOnce: true,
    probateTerm: 'Probate',
    localNotes: 'Royal Derby Hospital is the main hospital. Markeaton Crematorium serves the city.',
  },
  {
    slug: 'oxford',
    name: 'Oxford',
    region: 'South East England',
    nation: 'England',
    registrarName: 'Oxford Register Office',
    registrarAddress: 'Tidmarsh Lane, Oxford OX1 1NS',
    registrarPhone: '0345 241 2489',
    registrarUrl: 'https://www.oxfordshire.gov.uk/residents/births-deaths-and-ceremonies',
    councilName: 'Oxford City Council',
    councilPhone: '01865 249811',
    councilUrl: 'https://www.oxford.gov.uk',
    registrationDeadlineDays: 5,
    hasCoroner: true,
    hasTellUsOnce: true,
    probateTerm: 'Probate',
    localNotes: 'The John Radcliffe Hospital and Churchill Hospital are the main hospitals. Oxford Crematorium at Bayswater Road serves the area.',
  },
  {
    slug: 'cambridge',
    name: 'Cambridge',
    region: 'East of England',
    nation: 'England',
    registrarName: 'Cambridge Register Office',
    registrarAddress: 'Shire Hall, Castle Hill, Cambridge CB3 0AP',
    registrarPhone: '0345 045 1363',
    registrarUrl: 'https://www.cambridgeshire.gov.uk/births-deaths-and-ceremonies',
    councilName: 'Cambridge City Council',
    councilPhone: '01223 457000',
    councilUrl: 'https://www.cambridge.gov.uk',
    registrationDeadlineDays: 5,
    hasCoroner: true,
    hasTellUsOnce: true,
    probateTerm: 'Probate',
    localNotes: 'Addenbrooke\'s Hospital (Cambridge University Hospitals) is the main hospital. Cambridge City Crematorium serves the area.',
  },
  {
    slug: 'norwich',
    name: 'Norwich',
    region: 'East of England',
    nation: 'England',
    registrarName: 'Norwich Register Office',
    registrarAddress: 'County Hall, Martineau Lane, Norwich NR1 2DH',
    registrarPhone: '0344 800 8020',
    registrarUrl: 'https://www.norfolk.gov.uk/births-ceremonies-and-deaths',
    councilName: 'Norwich City Council',
    councilPhone: '0344 980 3333',
    councilUrl: 'https://www.norwich.gov.uk',
    registrationDeadlineDays: 5,
    hasCoroner: true,
    hasTellUsOnce: true,
    probateTerm: 'Probate',
    localNotes: 'The Norfolk and Norwich University Hospital is the main hospital. St Faith\'s Crematorium and Earlham Cemetery serve the city.',
  },
  {
    slug: 'brighton',
    name: 'Brighton and Hove',
    region: 'South East England',
    nation: 'England',
    registrarName: 'Brighton and Hove Register Office',
    registrarAddress: 'Brighton Town Hall, Bartholomews, Brighton BN1 1JA',
    registrarPhone: '01273 292016',
    registrarUrl: 'https://www.brighton-hove.gov.uk/births-deaths-marriages',
    councilName: 'Brighton and Hove City Council',
    councilPhone: '01273 290000',
    councilUrl: 'https://www.brighton-hove.gov.uk',
    registrationDeadlineDays: 5,
    hasCoroner: true,
    hasTellUsOnce: true,
    probateTerm: 'Probate',
    localNotes: 'Royal Sussex County Hospital is the main hospital. The Downs Crematorium and Woodvale Crematorium serve the area.',
  },
  {
    slug: 'york',
    name: 'York',
    region: 'Yorkshire and the Humber',
    nation: 'England',
    registrarName: 'York Register Office',
    registrarAddress: '56 Bootham, York YO30 7DA',
    registrarPhone: '01904 554455',
    registrarUrl: 'https://www.york.gov.uk/births-deaths-marriages',
    councilName: 'City of York Council',
    councilPhone: '01904 551550',
    councilUrl: 'https://www.york.gov.uk',
    registrationDeadlineDays: 5,
    hasCoroner: true,
    hasTellUsOnce: true,
    probateTerm: 'Probate',
    localNotes: 'York Hospital is the main hospital. York Crematorium at Bishopthorpe Road serves the city.',
  },
  {
    slug: 'bath',
    name: 'Bath',
    region: 'South West England',
    nation: 'England',
    registrarName: 'Bath Register Office',
    registrarAddress: 'The Guildhall, High Street, Bath BA1 5AW',
    registrarPhone: '01225 477234',
    registrarUrl: 'https://www.bathnes.gov.uk/births-deaths-and-ceremonies',
    councilName: 'Bath and North East Somerset Council',
    councilPhone: '01225 477000',
    councilUrl: 'https://www.bathnes.gov.uk',
    registrationDeadlineDays: 5,
    hasCoroner: true,
    hasTellUsOnce: true,
    probateTerm: 'Probate',
    localNotes: 'Royal United Hospital Bath is the main hospital. Haycombe Crematorium serves the area.',
  },
  {
    slug: 'exeter',
    name: 'Exeter',
    region: 'South West England',
    nation: 'England',
    registrarName: 'Exeter Register Office',
    registrarAddress: '1 Lower Summerlands, Heavitree Road, Exeter EX1 2LJ',
    registrarPhone: '0345 155 1002',
    registrarUrl: 'https://www.devon.gov.uk/births-deaths-and-ceremonies',
    councilName: 'Exeter City Council',
    councilPhone: '01392 277888',
    councilUrl: 'https://exeter.gov.uk',
    registrationDeadlineDays: 5,
    hasCoroner: true,
    hasTellUsOnce: true,
    probateTerm: 'Probate',
    localNotes: 'Royal Devon University Hospital (Wonford) is the main hospital. Exeter and Devon Crematorium serves the area.',
  },
  {
    slug: 'hull',
    name: 'Kingston upon Hull',
    region: 'Yorkshire and the Humber',
    nation: 'England',
    registrarName: 'Hull Register Office',
    registrarAddress: 'Kingston House, Bond Street, Hull HU1 3ER',
    registrarPhone: '01482 613053',
    registrarUrl: 'https://www.hull.gov.uk/births-deaths-marriages',
    councilName: 'Hull City Council',
    councilPhone: '01482 300300',
    councilUrl: 'https://www.hull.gov.uk',
    registrationDeadlineDays: 5,
    hasCoroner: true,
    hasTellUsOnce: true,
    probateTerm: 'Probate',
    localNotes: 'Hull Royal Infirmary is the main hospital. Chanterlands Crematorium and Haltemprice Crematorium serve the area.',
  },
  {
    slug: 'peterborough',
    name: 'Peterborough',
    region: 'East of England',
    nation: 'England',
    registrarName: 'Peterborough Register Office',
    registrarAddress: 'Town Hall, Bridge Street, Peterborough PE1 1HG',
    registrarPhone: '01733 747474',
    registrarUrl: 'https://www.peterborough.gov.uk/births-deaths-marriages',
    councilName: 'Peterborough City Council',
    councilPhone: '01733 747474',
    councilUrl: 'https://www.peterborough.gov.uk',
    registrationDeadlineDays: 5,
    hasCoroner: true,
    hasTellUsOnce: true,
    probateTerm: 'Probate',
    localNotes: 'Peterborough City Hospital is the main hospital. Peterborough Crematorium at Mowbray Road serves the area.',
  },
  {
    slug: 'milton-keynes',
    name: 'Milton Keynes',
    region: 'South East England',
    nation: 'England',
    registrarName: 'Milton Keynes Register Office',
    registrarAddress: 'Civic Offices, 1 Saxon Gate East, Milton Keynes MK9 3EJ',
    registrarPhone: '01908 237890',
    registrarUrl: 'https://www.milton-keynes.gov.uk/births-deaths-marriages',
    councilName: 'Milton Keynes City Council',
    councilPhone: '01908 691691',
    councilUrl: 'https://www.milton-keynes.gov.uk',
    registrationDeadlineDays: 5,
    hasCoroner: true,
    hasTellUsOnce: true,
    probateTerm: 'Probate',
    localNotes: 'Milton Keynes University Hospital is the main hospital. Crownhill Crematorium serves the area.',
  },
  {
    slug: 'chelmsford',
    name: 'Chelmsford',
    region: 'East of England',
    nation: 'England',
    registrarName: 'Chelmsford Register Office',
    registrarAddress: 'County Hall, Market Road, Chelmsford CM1 1QH',
    registrarPhone: '0345 603 7632',
    registrarUrl: 'https://www.essex.gov.uk/births-deaths-and-ceremonies',
    councilName: 'Chelmsford City Council',
    councilPhone: '01245 606606',
    councilUrl: 'https://www.chelmsford.gov.uk',
    registrationDeadlineDays: 5,
    hasCoroner: true,
    hasTellUsOnce: true,
    probateTerm: 'Probate',
    localNotes: 'Broomfield Hospital is the main hospital. Chelmsford Crematorium at Writtle Road serves the area.',
  },

  // Scotland
  {
    slug: 'edinburgh',
    name: 'Edinburgh',
    region: 'Scotland',
    nation: 'Scotland',
    registrarName: 'Edinburgh Registration Office',
    registrarAddress: 'New Register House, 3 West Register Street, Edinburgh EH1 3YT',
    registrarPhone: '0131 225 1382',
    registrarUrl: 'https://www.edinburgh.gov.uk/births-deaths-marriages',
    councilName: 'City of Edinburgh Council',
    councilPhone: '0131 200 2000',
    councilUrl: 'https://www.edinburgh.gov.uk',
    registrationDeadlineDays: 8,
    hasCoroner: false,
    hasTellUsOnce: true,
    probateTerm: 'Confirmation',
    localNotes: 'In Scotland, the process differs from England and Wales. Deaths are investigated by the Procurator Fiscal rather than a coroner. Probate is called "Confirmation". The Royal Infirmary of Edinburgh and Western General Hospital are the main hospitals. Mortonhall Crematorium and Warriston Crematorium serve the city.',
  },
  {
    slug: 'glasgow',
    name: 'Glasgow',
    region: 'Scotland',
    nation: 'Scotland',
    registrarName: 'Glasgow Registration Office',
    registrarAddress: 'City Chambers, George Square, Glasgow G2 1DU',
    registrarPhone: '0141 287 7651',
    registrarUrl: 'https://www.glasgow.gov.uk/births-deaths-marriages',
    councilName: 'Glasgow City Council',
    councilPhone: '0141 287 2000',
    councilUrl: 'https://www.glasgow.gov.uk',
    registrationDeadlineDays: 8,
    hasCoroner: false,
    hasTellUsOnce: true,
    probateTerm: 'Confirmation',
    localNotes: 'Glasgow is Scotland\'s largest city. The Queen Elizabeth University Hospital and Glasgow Royal Infirmary are the main hospitals. Deaths are investigated by the Procurator Fiscal rather than a coroner. Probate is called "Confirmation" in Scotland. Daldowie Crematorium, Linn Crematorium, and Clydebank Crematorium serve the area.',
  },
  {
    slug: 'aberdeen',
    name: 'Aberdeen',
    region: 'Scotland',
    nation: 'Scotland',
    registrarName: 'Aberdeen Registration Office',
    registrarAddress: 'Town House, Broad Street, Aberdeen AB10 1AQ',
    registrarPhone: '01224 522616',
    registrarUrl: 'https://www.aberdeencity.gov.uk/births-deaths-marriages',
    councilName: 'Aberdeen City Council',
    councilPhone: '01224 522000',
    councilUrl: 'https://www.aberdeencity.gov.uk',
    registrationDeadlineDays: 8,
    hasCoroner: false,
    hasTellUsOnce: true,
    probateTerm: 'Confirmation',
    localNotes: 'Aberdeen Royal Infirmary is the main hospital. In Scotland, deaths are investigated by the Procurator Fiscal, and probate is called "Confirmation". Aberdeen Crematorium at Skene Road serves the city.',
  },
  {
    slug: 'dundee',
    name: 'Dundee',
    region: 'Scotland',
    nation: 'Scotland',
    registrarName: 'Dundee Registration Office',
    registrarAddress: '89 Commercial Street, Dundee DD1 2AF',
    registrarPhone: '01382 434466',
    registrarUrl: 'https://www.dundeecity.gov.uk/births-deaths-marriages',
    councilName: 'Dundee City Council',
    councilPhone: '01382 434000',
    councilUrl: 'https://www.dundeecity.gov.uk',
    registrationDeadlineDays: 8,
    hasCoroner: false,
    hasTellUsOnce: true,
    probateTerm: 'Confirmation',
    localNotes: 'Ninewells Hospital is the main hospital. Dundee Crematorium at Macalpine Road serves the city. As with all of Scotland, deaths are investigated by the Procurator Fiscal and probate is called "Confirmation".',
  },
  {
    slug: 'inverness',
    name: 'Inverness',
    region: 'Scotland',
    nation: 'Scotland',
    registrarName: 'Inverness Registration Office',
    registrarAddress: 'Town House, High Street, Inverness IV1 1JJ',
    registrarPhone: '01349 886644',
    registrarUrl: 'https://www.highland.gov.uk/births-deaths-marriages',
    councilName: 'Highland Council',
    councilPhone: '01349 886606',
    councilUrl: 'https://www.highland.gov.uk',
    registrationDeadlineDays: 8,
    hasCoroner: false,
    hasTellUsOnce: true,
    probateTerm: 'Confirmation',
    localNotes: 'Raigmore Hospital is the main hospital for the Highlands. The Highland Council covers a vast area, so travel to the register office may require planning. Inverness Crematorium at Kilvean Road serves the city.',
  },
  {
    slug: 'stirling',
    name: 'Stirling',
    region: 'Scotland',
    nation: 'Scotland',
    registrarName: 'Stirling Registration Office',
    registrarAddress: 'Viewforth, Stirling FK8 2ET',
    registrarPhone: '01786 233066',
    registrarUrl: 'https://www.stirling.gov.uk/births-deaths-marriages',
    councilName: 'Stirling Council',
    councilPhone: '01786 404040',
    councilUrl: 'https://www.stirling.gov.uk',
    registrationDeadlineDays: 8,
    hasCoroner: false,
    hasTellUsOnce: true,
    probateTerm: 'Confirmation',
    localNotes: 'Forth Valley Royal Hospital in Larbert is the nearest major hospital. As with all of Scotland, the Procurator Fiscal investigates deaths and probate is called "Confirmation".',
  },

  // Wales
  {
    slug: 'cardiff',
    name: 'Cardiff',
    region: 'Wales',
    nation: 'Wales',
    registrarName: 'Cardiff Register Office',
    registrarAddress: 'City Hall, Cathays Park, Cardiff CF10 3ND',
    registrarPhone: '029 2087 1680',
    registrarUrl: 'https://www.cardiff.gov.uk/births-deaths-marriages',
    councilName: 'Cardiff Council',
    councilPhone: '029 2087 2087',
    councilUrl: 'https://www.cardiff.gov.uk',
    registrationDeadlineDays: 5,
    hasCoroner: true,
    hasTellUsOnce: true,
    probateTerm: 'Probate',
    localNotes: 'University Hospital of Wales and University Hospital Llandough are the main hospitals. Thornhill Crematorium serves the city. Wales follows the same death registration and probate rules as England.',
  },
  {
    slug: 'swansea',
    name: 'Swansea',
    region: 'Wales',
    nation: 'Wales',
    registrarName: 'Swansea Register Office',
    registrarAddress: 'County Hall, Oystermouth Road, Swansea SA1 3SN',
    registrarPhone: '01792 636369',
    registrarUrl: 'https://www.swansea.gov.uk/births-deaths-marriages',
    councilName: 'Swansea Council',
    councilPhone: '01792 636000',
    councilUrl: 'https://www.swansea.gov.uk',
    registrationDeadlineDays: 5,
    hasCoroner: true,
    hasTellUsOnce: true,
    probateTerm: 'Probate',
    localNotes: 'Morriston Hospital is the main hospital. Swansea Crematorium at Sketty serves the city. Wales follows the same registration and probate rules as England.',
  },
  {
    slug: 'newport',
    name: 'Newport',
    region: 'Wales',
    nation: 'Wales',
    registrarName: 'Newport Register Office',
    registrarAddress: 'Civic Centre, Godfrey Road, Newport NP20 4UR',
    registrarPhone: '01633 656656',
    registrarUrl: 'https://www.newport.gov.uk/births-deaths-marriages',
    councilName: 'Newport City Council',
    councilPhone: '01633 656656',
    councilUrl: 'https://www.newport.gov.uk',
    registrationDeadlineDays: 5,
    hasCoroner: true,
    hasTellUsOnce: true,
    probateTerm: 'Probate',
    localNotes: 'Royal Gwent Hospital is the main hospital. Gwent Crematorium at Croesyceiliog serves the area.',
  },
  {
    slug: 'wrexham',
    name: 'Wrexham',
    region: 'Wales',
    nation: 'Wales',
    registrarName: 'Wrexham Register Office',
    registrarAddress: 'Llwyn Isaf, High Street, Wrexham LL13 8LG',
    registrarPhone: '01978 292920',
    registrarUrl: 'https://www.wrexham.gov.uk/births-deaths-marriages',
    councilName: 'Wrexham County Borough Council',
    councilPhone: '01978 292000',
    councilUrl: 'https://www.wrexham.gov.uk',
    registrationDeadlineDays: 5,
    hasCoroner: true,
    hasTellUsOnce: true,
    probateTerm: 'Probate',
    localNotes: 'Wrexham Maelor Hospital is the main hospital. Wrexham Crematorium at Pentre Bychan serves the area.',
  },
  {
    slug: 'bangor',
    name: 'Bangor',
    region: 'Wales',
    nation: 'Wales',
    registrarName: 'Bangor Register Office',
    registrarAddress: 'Council Offices, Ffordd Gwynedd, Bangor LL57 1DT',
    registrarPhone: '01286 679535',
    registrarUrl: 'https://www.gwynedd.llyw.cymru/en/births-deaths-marriages',
    councilName: 'Cyngor Gwynedd Council',
    councilPhone: '01766 771000',
    councilUrl: 'https://www.gwynedd.llyw.cymru',
    registrationDeadlineDays: 5,
    hasCoroner: true,
    hasTellUsOnce: true,
    probateTerm: 'Probate',
    localNotes: 'Ysbyty Gwynedd in Bangor is the main hospital. Services are available in both Welsh and English. Bangor Crematorium serves the area.',
  },

  // Northern Ireland
  {
    slug: 'belfast',
    name: 'Belfast',
    region: 'Northern Ireland',
    nation: 'Northern Ireland',
    registrarName: 'Belfast Register Office',
    registrarAddress: 'Oxford House, 49-55 Chichester Street, Belfast BT1 4HL',
    registrarPhone: '028 9151 3101',
    registrarUrl: 'https://www.nidirect.gov.uk/articles/registering-death',
    councilName: 'Belfast City Council',
    councilPhone: '028 9032 0202',
    councilUrl: 'https://www.belfastcity.gov.uk',
    registrationDeadlineDays: 5,
    hasCoroner: true,
    hasTellUsOnce: false,
    probateTerm: 'Probate',
    localNotes: 'Northern Ireland has different procedures from the rest of the UK. The Tell Us Once service is not available here, so you will need to notify each organisation individually. The Royal Victoria Hospital and Belfast City Hospital are the main hospitals. Roselawn Crematorium is the city\'s main crematorium. Probate is handled by the Probate Office at Royal Courts of Justice, Chichester Street.',
  },
  {
    slug: 'derry',
    name: 'Derry/Londonderry',
    region: 'Northern Ireland',
    nation: 'Northern Ireland',
    registrarName: 'Derry Register Office',
    registrarAddress: '36-38 Bishop Street, Derry BT48 6PP',
    registrarPhone: '028 7126 1050',
    registrarUrl: 'https://www.nidirect.gov.uk/articles/registering-death',
    councilName: 'Derry City and Strabane District Council',
    councilPhone: '028 7125 3253',
    councilUrl: 'https://www.derrystrabane.com',
    registrationDeadlineDays: 5,
    hasCoroner: true,
    hasTellUsOnce: false,
    probateTerm: 'Probate',
    localNotes: 'Altnagelvin Area Hospital is the main hospital. Tell Us Once is not available in Northern Ireland, so you must notify each organisation separately. The District Probate Registry at the Bishop Street Courthouse handles probate applications for the north-west.',
  },
  {
    slug: 'lisburn',
    name: 'Lisburn',
    region: 'Northern Ireland',
    nation: 'Northern Ireland',
    registrarName: 'Lisburn Register Office',
    registrarAddress: 'Island Civic Centre, The Island, Lisburn BT27 4RL',
    registrarPhone: '028 9250 9250',
    registrarUrl: 'https://www.nidirect.gov.uk/articles/registering-death',
    councilName: 'Lisburn and Castlereagh City Council',
    councilPhone: '028 9250 9250',
    councilUrl: 'https://www.lisburncastlereagh.gov.uk',
    registrationDeadlineDays: 5,
    hasCoroner: true,
    hasTellUsOnce: false,
    probateTerm: 'Probate',
    localNotes: 'Lagan Valley Hospital is the main local hospital, though many patients are referred to Belfast hospitals. Tell Us Once is not available in Northern Ireland.',
  },
  {
    slug: 'newry',
    name: 'Newry',
    region: 'Northern Ireland',
    nation: 'Northern Ireland',
    registrarName: 'Newry Register Office',
    registrarAddress: 'O\'Hagan House, Monaghan Row, Newry BT35 8DJ',
    registrarPhone: '028 3031 3170',
    registrarUrl: 'https://www.nidirect.gov.uk/articles/registering-death',
    councilName: 'Newry, Mourne and Down District Council',
    councilPhone: '028 3031 3000',
    councilUrl: 'https://www.newrymournedown.org',
    registrationDeadlineDays: 5,
    hasCoroner: true,
    hasTellUsOnce: false,
    probateTerm: 'Probate',
    localNotes: 'Daisy Hill Hospital is the main local hospital. Tell Us Once is not available in Northern Ireland.',
  },

  // More English cities for coverage
  {
    slug: 'gloucester',
    name: 'Gloucester',
    region: 'South West England',
    nation: 'England',
    registrarName: 'Gloucester Register Office',
    registrarAddress: 'Shire Hall, Westgate Street, Gloucester GL1 2TG',
    registrarPhone: '01452 425025',
    registrarUrl: 'https://www.gloucestershire.gov.uk/births-deaths-and-ceremonies',
    councilName: 'Gloucester City Council',
    councilPhone: '01452 396396',
    councilUrl: 'https://www.gloucester.gov.uk',
    registrationDeadlineDays: 5,
    hasCoroner: true,
    hasTellUsOnce: true,
    probateTerm: 'Probate',
    localNotes: 'Gloucestershire Royal Hospital is the main hospital. Gloucester Crematorium serves the area.',
  },
  {
    slug: 'worcester',
    name: 'Worcester',
    region: 'West Midlands',
    nation: 'England',
    registrarName: 'Worcester Register Office',
    registrarAddress: 'County Hall, Spetchley Road, Worcester WR5 2NP',
    registrarPhone: '01905 765765',
    registrarUrl: 'https://www.worcestershire.gov.uk/births-deaths-marriages',
    councilName: 'Worcester City Council',
    councilPhone: '01905 722233',
    councilUrl: 'https://www.worcester.gov.uk',
    registrationDeadlineDays: 5,
    hasCoroner: true,
    hasTellUsOnce: true,
    probateTerm: 'Probate',
    localNotes: 'Worcestershire Royal Hospital is the main hospital. Worcester Crematorium at Astwood Road serves the area.',
  },
  {
    slug: 'lincoln',
    name: 'Lincoln',
    region: 'East Midlands',
    nation: 'England',
    registrarName: 'Lincoln Register Office',
    registrarAddress: 'County Offices, Newland, Lincoln LN1 1YL',
    registrarPhone: '01522 782244',
    registrarUrl: 'https://www.lincolnshire.gov.uk/births-deaths-marriages',
    councilName: 'City of Lincoln Council',
    councilPhone: '01522 881188',
    councilUrl: 'https://www.lincoln.gov.uk',
    registrationDeadlineDays: 5,
    hasCoroner: true,
    hasTellUsOnce: true,
    probateTerm: 'Probate',
    localNotes: 'Lincoln County Hospital is the main hospital. Lincoln Crematorium at Washingborough Road serves the area.',
  },
  {
    slug: 'salisbury',
    name: 'Salisbury',
    region: 'South West England',
    nation: 'England',
    registrarName: 'Salisbury Register Office',
    registrarAddress: 'Bourne Hill, Salisbury SP1 3UZ',
    registrarPhone: '0300 456 0100',
    registrarUrl: 'https://www.wiltshire.gov.uk/births-deaths-marriages',
    councilName: 'Wiltshire Council',
    councilPhone: '0300 456 0100',
    councilUrl: 'https://www.wiltshire.gov.uk',
    registrationDeadlineDays: 5,
    hasCoroner: true,
    hasTellUsOnce: true,
    probateTerm: 'Probate',
    localNotes: 'Salisbury District Hospital is the main hospital. Salisbury Crematorium serves the area.',
  },
  {
    slug: 'chester',
    name: 'Chester',
    region: 'North West England',
    nation: 'England',
    registrarName: 'Chester Register Office',
    registrarAddress: 'HQ, Nicholas Street, Chester CH1 2NP',
    registrarPhone: '0300 123 7025',
    registrarUrl: 'https://www.cheshirewestandchester.gov.uk/births-deaths-marriages',
    councilName: 'Cheshire West and Chester Council',
    councilPhone: '0300 123 8123',
    councilUrl: 'https://www.cheshirewestandchester.gov.uk',
    registrationDeadlineDays: 5,
    hasCoroner: true,
    hasTellUsOnce: true,
    probateTerm: 'Probate',
    localNotes: 'The Countess of Chester Hospital is the main hospital. Blacon Crematorium serves the area.',
  },
  {
    slug: 'carlisle',
    name: 'Carlisle',
    region: 'North West England',
    nation: 'England',
    registrarName: 'Carlisle Register Office',
    registrarAddress: 'The Courts, English Street, Carlisle CA3 8NA',
    registrarPhone: '01228 221122',
    registrarUrl: 'https://www.cumberland.gov.uk/births-deaths-marriages',
    councilName: 'Cumberland Council',
    councilPhone: '01228 606060',
    councilUrl: 'https://www.cumberland.gov.uk',
    registrationDeadlineDays: 5,
    hasCoroner: true,
    hasTellUsOnce: true,
    probateTerm: 'Probate',
    localNotes: 'Cumberland Infirmary is the main hospital. Carlisle Crematorium at Richardson Street serves the area.',
  },
  {
    slug: 'durham',
    name: 'Durham',
    region: 'North East England',
    nation: 'England',
    registrarName: 'Durham Register Office',
    registrarAddress: 'County Hall, Aykley Heads, Durham DH1 5UL',
    registrarPhone: '03000 266000',
    registrarUrl: 'https://www.durham.gov.uk/births-deaths-marriages',
    councilName: 'Durham County Council',
    councilPhone: '03000 260000',
    councilUrl: 'https://www.durham.gov.uk',
    registrationDeadlineDays: 5,
    hasCoroner: true,
    hasTellUsOnce: true,
    probateTerm: 'Probate',
    localNotes: 'University Hospital of North Durham is the main hospital. Durham Crematorium at South Road serves the area.',
  },
  {
    slug: 'middlesbrough',
    name: 'Middlesbrough',
    region: 'North East England',
    nation: 'England',
    registrarName: 'Middlesbrough Register Office',
    registrarAddress: 'Middlesbrough Town Hall, Albert Road, Middlesbrough TS1 2QJ',
    registrarPhone: '01642 728088',
    registrarUrl: 'https://www.middlesbrough.gov.uk/births-deaths-marriages',
    councilName: 'Middlesbrough Council',
    councilPhone: '01642 245432',
    councilUrl: 'https://www.middlesbrough.gov.uk',
    registrationDeadlineDays: 5,
    hasCoroner: true,
    hasTellUsOnce: true,
    probateTerm: 'Probate',
    localNotes: 'James Cook University Hospital is the main hospital. Teesside Crematorium at Acklam Road serves the area.',
  },
  {
    slug: 'blackpool',
    name: 'Blackpool',
    region: 'North West England',
    nation: 'England',
    registrarName: 'Blackpool Register Office',
    registrarAddress: 'Blackpool Town Hall, Talbot Square, Blackpool FY1 1AD',
    registrarPhone: '01253 477177',
    registrarUrl: 'https://www.blackpool.gov.uk/births-deaths-marriages',
    councilName: 'Blackpool Council',
    councilPhone: '01253 477477',
    councilUrl: 'https://www.blackpool.gov.uk',
    registrationDeadlineDays: 5,
    hasCoroner: true,
    hasTellUsOnce: true,
    probateTerm: 'Probate',
    localNotes: 'Blackpool Victoria Hospital is the main hospital. Carleton Crematorium serves the area.',
  },
  {
    slug: 'ipswich',
    name: 'Ipswich',
    region: 'East of England',
    nation: 'England',
    registrarName: 'Ipswich Register Office',
    registrarAddress: 'Endeavour House, 8 Russell Road, Ipswich IP1 2BX',
    registrarPhone: '0345 607 2050',
    registrarUrl: 'https://www.suffolk.gov.uk/births-deaths-and-ceremonies',
    councilName: 'Ipswich Borough Council',
    councilPhone: '01473 432000',
    councilUrl: 'https://www.ipswich.gov.uk',
    registrationDeadlineDays: 5,
    hasCoroner: true,
    hasTellUsOnce: true,
    probateTerm: 'Probate',
    localNotes: 'Ipswich Hospital is the main hospital. Ipswich Crematorium at Cemetery Road serves the area.',
  },
  {
    slug: 'luton',
    name: 'Luton',
    region: 'East of England',
    nation: 'England',
    registrarName: 'Luton Register Office',
    registrarAddress: '6 George Street West, Luton LU1 2BJ',
    registrarPhone: '01582 547222',
    registrarUrl: 'https://www.luton.gov.uk/births-deaths-marriages',
    councilName: 'Luton Borough Council',
    councilPhone: '01582 546000',
    councilUrl: 'https://www.luton.gov.uk',
    registrationDeadlineDays: 5,
    hasCoroner: true,
    hasTellUsOnce: true,
    probateTerm: 'Probate',
    localNotes: 'Luton and Dunstable University Hospital is the main hospital. The Vale Crematorium at Butterfield Green Road serves the area. Luton has a diverse population with established funeral services for various faiths.',
  },
  {
    slug: 'warrington',
    name: 'Warrington',
    region: 'North West England',
    nation: 'England',
    registrarName: 'Warrington Register Office',
    registrarAddress: 'Town Hall, Sankey Street, Warrington WA1 1UH',
    registrarPhone: '01925 442 586',
    registrarUrl: 'https://www.warrington.gov.uk/births-deaths-marriages',
    councilName: 'Warrington Borough Council',
    councilPhone: '01925 444400',
    councilUrl: 'https://www.warrington.gov.uk',
    registrationDeadlineDays: 5,
    hasCoroner: true,
    hasTellUsOnce: true,
    probateTerm: 'Probate',
    localNotes: 'Warrington Hospital is the main hospital. Walton Lea Crematorium serves the area.',
  },
];

export function getCityBySlug(slug: string): CityData | undefined {
  return cities.find(c => c.slug === slug);
}

export function getCitiesByNation(nation: string): CityData[] {
  return cities.filter(c => c.nation === nation);
}

export function getCitiesByRegion(region: string): CityData[] {
  return cities.filter(c => c.region === region);
}

export function getAllRegions(): string[] {
  const regions = new Set(cities.map(c => c.region));
  return Array.from(regions).sort();
}
