export interface RegistrarOffice {
  name: string;
  address: string;
  phone: string;
  url: string;
}

export interface CountyData {
  slug: string;
  name: string;
  nation: 'England' | 'Wales';
  registrarOffices: RegistrarOffice[];
  councilName: string;
  councilPhone: string;
  councilUrl: string;
  registrationDeadlineDays: number;
  majorTowns: string[];
  localNotes?: string;
}

export const counties: CountyData[] = [
  // ===== ENGLAND (39 + extras to reach 45) =====
  {
    slug: 'bedfordshire',
    name: 'Bedfordshire',
    nation: 'England',
    registrarOffices: [
      { name: 'Bedford Register Office', address: '3 St Paul\'s Square, Bedford MK40 1SL', phone: '01234 228448', url: 'https://www.bedford.gov.uk/births-deaths-marriages' },
      { name: 'Luton Register Office', address: '6 George Street West, Luton LU1 2BJ', phone: '01582 547222', url: 'https://www.luton.gov.uk/births-deaths-marriages' },
      { name: 'Dunstable Register Office', address: 'Grove House, 76 High Street North, Dunstable LU6 1NF', phone: '0300 300 8305', url: 'https://www.centralbedfordshire.gov.uk/births-deaths-marriages' },
    ],
    councilName: 'Bedford Borough Council',
    councilPhone: '01234 267422',
    councilUrl: 'https://www.bedford.gov.uk',
    registrationDeadlineDays: 5,
    majorTowns: ['Bedford', 'Luton', 'Dunstable', 'Leighton Buzzard', 'Biggleswade'],
  },
  {
    slug: 'berkshire',
    name: 'Berkshire',
    nation: 'England',
    registrarOffices: [
      { name: 'Reading Register Office', address: 'Yeomanry House, 131 Castle Hill, Reading RG1 7TJ', phone: '0118 937 3304', url: 'https://www.reading.gov.uk/births-deaths-marriages' },
      { name: 'Slough Register Office', address: 'The Centre, Farnham Road, Slough SL1 4UT', phone: '01753 875380', url: 'https://www.slough.gov.uk/births-deaths-marriages' },
      { name: 'Windsor Register Office', address: 'The Guildhall, High Street, Windsor SL4 1LR', phone: '01628 796400', url: 'https://www.rbwm.gov.uk/births-deaths-marriages' },
    ],
    councilName: 'Reading Borough Council',
    councilPhone: '0118 937 3787',
    councilUrl: 'https://www.reading.gov.uk',
    registrationDeadlineDays: 5,
    majorTowns: ['Reading', 'Slough', 'Windsor', 'Maidenhead', 'Bracknell'],
  },
  {
    slug: 'bristol',
    name: 'Bristol',
    nation: 'England',
    registrarOffices: [
      { name: 'Bristol Register Office', address: 'Quakers Friars, Broadmead, Bristol BS1 3BU', phone: '0117 922 2800', url: 'https://www.bristol.gov.uk/births-deaths-marriages' },
    ],
    councilName: 'Bristol City Council',
    councilPhone: '0117 922 2000',
    councilUrl: 'https://www.bristol.gov.uk',
    registrationDeadlineDays: 5,
    majorTowns: ['Bristol', 'Clifton', 'Bedminster', 'Fishponds', 'Henbury'],
    localNotes: 'Bristol is a unitary authority with a single register office covering the whole city. The Bristol Royal Infirmary and Southmead Hospital are the main hospitals.',
  },
  {
    slug: 'buckinghamshire',
    name: 'Buckinghamshire',
    nation: 'England',
    registrarOffices: [
      { name: 'Aylesbury Register Office', address: 'Walton Street, Aylesbury HP20 1UA', phone: '01296 382481', url: 'https://www.buckinghamshire.gov.uk/births-deaths-marriages' },
      { name: 'High Wycombe Register Office', address: 'The Guildhall, Queen Victoria Road, High Wycombe HP11 1BB', phone: '01494 475092', url: 'https://www.buckinghamshire.gov.uk/births-deaths-marriages' },
    ],
    councilName: 'Buckinghamshire Council',
    councilPhone: '01296 395000',
    councilUrl: 'https://www.buckinghamshire.gov.uk',
    registrationDeadlineDays: 5,
    majorTowns: ['Aylesbury', 'High Wycombe', 'Milton Keynes', 'Amersham', 'Chesham'],
  },
  {
    slug: 'cambridgeshire',
    name: 'Cambridgeshire',
    nation: 'England',
    registrarOffices: [
      { name: 'Cambridge Register Office', address: 'Shire Hall, Castle Hill, Cambridge CB3 0AP', phone: '0345 045 1363', url: 'https://www.cambridgeshire.gov.uk/births-deaths-marriages' },
      { name: 'Peterborough Register Office', address: 'Town Hall, Bridge Street, Peterborough PE1 1HF', phone: '01733 747474', url: 'https://www.peterborough.gov.uk/births-deaths-marriages' },
    ],
    councilName: 'Cambridgeshire County Council',
    councilPhone: '0345 045 5200',
    councilUrl: 'https://www.cambridgeshire.gov.uk',
    registrationDeadlineDays: 5,
    majorTowns: ['Cambridge', 'Peterborough', 'Huntingdon', 'Ely', 'Wisbech'],
  },
  {
    slug: 'cheshire',
    name: 'Cheshire',
    nation: 'England',
    registrarOffices: [
      { name: 'Chester Register Office', address: 'HQ, Nicholas Street, Chester CH1 2NP', phone: '0300 123 7025', url: 'https://www.cheshirewestandchester.gov.uk/births-deaths-marriages' },
      { name: 'Crewe Register Office', address: 'Delamere House, Delamere Street, Crewe CW1 2JZ', phone: '0300 123 5013', url: 'https://www.cheshireeast.gov.uk/births-deaths-marriages' },
      { name: 'Macclesfield Register Office', address: 'Town Hall, Market Place, Macclesfield SK10 1EA', phone: '0300 123 5013', url: 'https://www.cheshireeast.gov.uk/births-deaths-marriages' },
    ],
    councilName: 'Cheshire West and Chester Council',
    councilPhone: '0300 123 8123',
    councilUrl: 'https://www.cheshirewestandchester.gov.uk',
    registrationDeadlineDays: 5,
    majorTowns: ['Chester', 'Crewe', 'Macclesfield', 'Warrington', 'Ellesmere Port'],
  },
  {
    slug: 'cornwall',
    name: 'Cornwall',
    nation: 'England',
    registrarOffices: [
      { name: 'Truro Register Office', address: 'New County Hall, Treyew Road, Truro TR1 3AY', phone: '0300 1234 181', url: 'https://www.cornwall.gov.uk/births-deaths-marriages' },
      { name: 'Penzance Register Office', address: 'St Clare, Penzance TR18 3QW', phone: '0300 1234 181', url: 'https://www.cornwall.gov.uk/births-deaths-marriages' },
    ],
    councilName: 'Cornwall Council',
    councilPhone: '0300 1234 100',
    councilUrl: 'https://www.cornwall.gov.uk',
    registrationDeadlineDays: 5,
    majorTowns: ['Truro', 'Penzance', 'Falmouth', 'Newquay', 'St Austell'],
    localNotes: 'Cornwall is a large rural county and some registrar offices may require advance booking. The Royal Cornwall Hospital at Treliske is the main hospital.',
  },
  {
    slug: 'cumbria',
    name: 'Cumbria',
    nation: 'England',
    registrarOffices: [
      { name: 'Carlisle Register Office', address: 'The Courts, English Street, Carlisle CA3 8NA', phone: '01228 221122', url: 'https://www.cumberland.gov.uk/births-deaths-marriages' },
      { name: 'Kendal Register Office', address: 'County Hall, Kendal LA9 4RQ', phone: '01539 713567', url: 'https://www.westmorland.gov.uk/births-deaths-marriages' },
      { name: 'Barrow Register Office', address: 'Town Hall, Duke Street, Barrow-in-Furness LA14 2LD', phone: '01229 404370', url: 'https://www.westmorland.gov.uk/births-deaths-marriages' },
    ],
    councilName: 'Cumberland Council',
    councilPhone: '01228 606060',
    councilUrl: 'https://www.cumberland.gov.uk',
    registrationDeadlineDays: 5,
    majorTowns: ['Carlisle', 'Kendal', 'Barrow-in-Furness', 'Penrith', 'Workington'],
  },
  {
    slug: 'derbyshire',
    name: 'Derbyshire',
    nation: 'England',
    registrarOffices: [
      { name: 'Derby Register Office', address: 'Council House, Corporation Street, Derby DE1 2FS', phone: '01332 641672', url: 'https://www.derby.gov.uk/births-deaths-marriages' },
      { name: 'Chesterfield Register Office', address: 'New Beetwell Street, Chesterfield S40 1QJ', phone: '01629 533190', url: 'https://www.derbyshire.gov.uk/births-deaths-marriages' },
    ],
    councilName: 'Derbyshire County Council',
    councilPhone: '01629 533190',
    councilUrl: 'https://www.derbyshire.gov.uk',
    registrationDeadlineDays: 5,
    majorTowns: ['Derby', 'Chesterfield', 'Buxton', 'Ilkeston', 'Long Eaton'],
  },
  {
    slug: 'devon',
    name: 'Devon',
    nation: 'England',
    registrarOffices: [
      { name: 'Exeter Register Office', address: '1 Lower Summerlands, Heavitree Road, Exeter EX1 2LJ', phone: '0345 155 1002', url: 'https://www.devon.gov.uk/births-deaths-marriages' },
      { name: 'Plymouth Register Office', address: 'Lockyer Street, Plymouth PL1 2QD', phone: '01752 307400', url: 'https://www.plymouth.gov.uk/births-deaths-marriages' },
      { name: 'Torquay Register Office', address: 'Oldway Mansion, Torquay Road, Paignton TQ3 2TE', phone: '01803 207920', url: 'https://www.torbay.gov.uk/births-deaths-marriages' },
    ],
    councilName: 'Devon County Council',
    councilPhone: '0345 155 1015',
    councilUrl: 'https://www.devon.gov.uk',
    registrationDeadlineDays: 5,
    majorTowns: ['Exeter', 'Plymouth', 'Torquay', 'Barnstaple', 'Tiverton'],
  },
  {
    slug: 'dorset',
    name: 'Dorset',
    nation: 'England',
    registrarOffices: [
      { name: 'Dorchester Register Office', address: 'County Hall, Colliton Park, Dorchester DT1 1XJ', phone: '01305 225157', url: 'https://www.dorsetcouncil.gov.uk/births-deaths-marriages' },
      { name: 'Bournemouth Register Office', address: 'Town Hall, Bourne Avenue, Bournemouth BH2 6DY', phone: '01202 454744', url: 'https://www.bcpcouncil.gov.uk/births-deaths-marriages' },
    ],
    councilName: 'Dorset Council',
    councilPhone: '01305 221000',
    councilUrl: 'https://www.dorsetcouncil.gov.uk',
    registrationDeadlineDays: 5,
    majorTowns: ['Dorchester', 'Bournemouth', 'Poole', 'Weymouth', 'Christchurch'],
  },
  {
    slug: 'durham',
    name: 'Durham',
    nation: 'England',
    registrarOffices: [
      { name: 'Durham Register Office', address: 'County Hall, Aykley Heads, Durham DH1 5UL', phone: '03000 266000', url: 'https://www.durham.gov.uk/births-deaths-marriages' },
      { name: 'Bishop Auckland Register Office', address: 'Town Hall, Market Place, Bishop Auckland DL14 7NP', phone: '03000 266000', url: 'https://www.durham.gov.uk/births-deaths-marriages' },
    ],
    councilName: 'Durham County Council',
    councilPhone: '03000 260000',
    councilUrl: 'https://www.durham.gov.uk',
    registrationDeadlineDays: 5,
    majorTowns: ['Durham', 'Bishop Auckland', 'Consett', 'Newton Aycliffe', 'Seaham'],
  },
  {
    slug: 'east-riding-of-yorkshire',
    name: 'East Riding of Yorkshire',
    nation: 'England',
    registrarOffices: [
      { name: 'Beverley Register Office', address: 'County Hall, Cross Street, Beverley HU17 9BA', phone: '01482 393810', url: 'https://www.eastriding.gov.uk/births-deaths-marriages' },
      { name: 'Bridlington Register Office', address: 'Town Hall, Quay Road, Bridlington YO16 4LP', phone: '01482 393810', url: 'https://www.eastriding.gov.uk/births-deaths-marriages' },
    ],
    councilName: 'East Riding of Yorkshire Council',
    councilPhone: '01482 393939',
    councilUrl: 'https://www.eastriding.gov.uk',
    registrationDeadlineDays: 5,
    majorTowns: ['Beverley', 'Bridlington', 'Goole', 'Driffield', 'Hessle'],
  },
  {
    slug: 'east-sussex',
    name: 'East Sussex',
    nation: 'England',
    registrarOffices: [
      { name: 'Lewes Register Office', address: 'Southover Grange, Southover High Street, Lewes BN7 1TP', phone: '01273 481610', url: 'https://www.eastsussex.gov.uk/births-deaths-marriages' },
      { name: 'Brighton Register Office', address: 'Brighton Town Hall, Bartholomew Square, Brighton BN1 1JA', phone: '01273 290992', url: 'https://www.brighton-hove.gov.uk/births-deaths-marriages' },
      { name: 'Hastings Register Office', address: 'Town Hall, Queen\'s Road, Hastings TN34 1QR', phone: '01273 481610', url: 'https://www.eastsussex.gov.uk/births-deaths-marriages' },
    ],
    councilName: 'East Sussex County Council',
    councilPhone: '01273 481000',
    councilUrl: 'https://www.eastsussex.gov.uk',
    registrationDeadlineDays: 5,
    majorTowns: ['Brighton', 'Lewes', 'Hastings', 'Eastbourne', 'Bexhill-on-Sea'],
  },
  {
    slug: 'essex',
    name: 'Essex',
    nation: 'England',
    registrarOffices: [
      { name: 'Chelmsford Register Office', address: 'County Hall, Market Road, Chelmsford CM1 1QH', phone: '0345 603 7632', url: 'https://www.essex.gov.uk/births-deaths-marriages' },
      { name: 'Southend Register Office', address: 'Southend Civic Centre, Victoria Avenue, Southend-on-Sea SS2 6ER', phone: '01702 215008', url: 'https://www.southend.gov.uk/births-deaths-marriages' },
      { name: 'Colchester Register Office', address: 'Stanwell House, Stanwell Street, Colchester CO2 7DL', phone: '0345 603 7632', url: 'https://www.essex.gov.uk/births-deaths-marriages' },
    ],
    councilName: 'Essex County Council',
    councilPhone: '0345 743 0430',
    councilUrl: 'https://www.essex.gov.uk',
    registrationDeadlineDays: 5,
    majorTowns: ['Chelmsford', 'Southend-on-Sea', 'Colchester', 'Basildon', 'Harlow'],
  },
  {
    slug: 'gloucestershire',
    name: 'Gloucestershire',
    nation: 'England',
    registrarOffices: [
      { name: 'Gloucester Register Office', address: 'Shire Hall, Westgate Street, Gloucester GL1 2TG', phone: '01452 425920', url: 'https://www.gloucestershire.gov.uk/births-deaths-marriages' },
      { name: 'Cheltenham Register Office', address: 'St George\'s Place, Cheltenham GL50 3PN', phone: '01242 532474', url: 'https://www.gloucestershire.gov.uk/births-deaths-marriages' },
    ],
    councilName: 'Gloucestershire County Council',
    councilPhone: '01452 425000',
    councilUrl: 'https://www.gloucestershire.gov.uk',
    registrationDeadlineDays: 5,
    majorTowns: ['Gloucester', 'Cheltenham', 'Stroud', 'Cirencester', 'Tewkesbury'],
  },
  {
    slug: 'greater-london',
    name: 'Greater London',
    nation: 'England',
    registrarOffices: [
      { name: 'Westminster Register Office', address: 'Westminster City Hall, 64 Victoria Street, London SW1E 6QP', phone: '020 7641 7500', url: 'https://www.westminster.gov.uk/births-deaths-marriages' },
      { name: 'Camden Register Office', address: 'Camden Town Hall, Judd Street, London WC1H 9JE', phone: '020 7974 1601', url: 'https://www.camden.gov.uk/births-deaths-marriages' },
      { name: 'Croydon Register Office', address: 'Croydon Clocktower, Katharine Street, Croydon CR9 1ET', phone: '020 8726 6300', url: 'https://www.croydon.gov.uk/births-deaths-marriages' },
    ],
    councilName: 'Greater London Authority',
    councilPhone: '020 7983 4000',
    councilUrl: 'https://www.london.gov.uk',
    registrationDeadlineDays: 5,
    majorTowns: ['Westminster', 'Camden', 'Croydon', 'Bromley', 'Greenwich'],
    localNotes: 'Greater London has 33 borough registrars, each covering their own area. You must register the death in the borough where the person died, not where they lived. Contact the relevant borough council to find your local register office.',
  },
  {
    slug: 'greater-manchester',
    name: 'Greater Manchester',
    nation: 'England',
    registrarOffices: [
      { name: 'Manchester Register Office', address: 'Heron House, 47 Lloyd Street, Manchester M2 5LE', phone: '0161 234 7900', url: 'https://www.manchester.gov.uk/births-deaths-marriages' },
      { name: 'Bolton Register Office', address: 'Town Hall, Victoria Square, Bolton BL1 1RU', phone: '01204 338070', url: 'https://www.bolton.gov.uk/births-deaths-marriages' },
      { name: 'Stockport Register Office', address: 'Town Hall, Edward Street, Stockport SK1 3XE', phone: '0161 474 3055', url: 'https://www.stockport.gov.uk/births-deaths-marriages' },
    ],
    councilName: 'Manchester City Council',
    councilPhone: '0161 234 5000',
    councilUrl: 'https://www.manchester.gov.uk',
    registrationDeadlineDays: 5,
    majorTowns: ['Manchester', 'Bolton', 'Stockport', 'Oldham', 'Wigan'],
    localNotes: 'Greater Manchester has 10 metropolitan boroughs, each with its own register office. You must register the death in the borough where the person died.',
  },
  {
    slug: 'hampshire',
    name: 'Hampshire',
    nation: 'England',
    registrarOffices: [
      { name: 'Winchester Register Office', address: 'The Castle, Winchester SO23 8UJ', phone: '0300 555 1392', url: 'https://www.hants.gov.uk/births-deaths-marriages' },
      { name: 'Southampton Register Office', address: 'Bugle House, Bugle Street, Southampton SO14 2AJ', phone: '023 8083 2449', url: 'https://www.southampton.gov.uk/births-deaths-marriages' },
      { name: 'Portsmouth Register Office', address: 'Milldam House, Burnaby Road, Portsmouth PO1 3AF', phone: '023 9282 5301', url: 'https://www.portsmouth.gov.uk/births-deaths-marriages' },
    ],
    councilName: 'Hampshire County Council',
    councilPhone: '0300 555 1375',
    councilUrl: 'https://www.hants.gov.uk',
    registrationDeadlineDays: 5,
    majorTowns: ['Winchester', 'Southampton', 'Portsmouth', 'Basingstoke', 'Fareham'],
  },
  {
    slug: 'hertfordshire',
    name: 'Hertfordshire',
    nation: 'England',
    registrarOffices: [
      { name: 'Hertford Register Office', address: 'County Hall, Pegs Lane, Hertford SG13 8DE', phone: '0300 123 4042', url: 'https://www.hertfordshire.gov.uk/births-deaths-marriages' },
      { name: 'Watford Register Office', address: 'Town Hall, Watford WD17 3EX', phone: '0300 123 4042', url: 'https://www.hertfordshire.gov.uk/births-deaths-marriages' },
      { name: 'St Albans Register Office', address: 'Town Hall, St Peter\'s Street, St Albans AL1 3DJ', phone: '0300 123 4042', url: 'https://www.hertfordshire.gov.uk/births-deaths-marriages' },
    ],
    councilName: 'Hertfordshire County Council',
    councilPhone: '0300 123 4040',
    councilUrl: 'https://www.hertfordshire.gov.uk',
    registrationDeadlineDays: 5,
    majorTowns: ['Hertford', 'Watford', 'St Albans', 'Stevenage', 'Hemel Hempstead'],
  },
  {
    slug: 'isle-of-wight',
    name: 'Isle of Wight',
    nation: 'England',
    registrarOffices: [
      { name: 'Newport Register Office', address: 'County Hall, High Street, Newport PO30 1UD', phone: '01983 823380', url: 'https://www.iow.gov.uk/births-deaths-marriages' },
    ],
    councilName: 'Isle of Wight Council',
    councilPhone: '01983 821000',
    councilUrl: 'https://www.iow.gov.uk',
    registrationDeadlineDays: 5,
    majorTowns: ['Newport', 'Ryde', 'Cowes', 'Sandown', 'Ventnor'],
    localNotes: 'The Isle of Wight has a single register office in Newport. St Mary\'s Hospital is the island\'s main hospital. If a death occurs on the mainland, it must be registered there.',
  },
  {
    slug: 'kent',
    name: 'Kent',
    nation: 'England',
    registrarOffices: [
      { name: 'Maidstone Register Office', address: 'County Hall, Maidstone ME14 1XQ', phone: '03000 419494', url: 'https://www.kent.gov.uk/births-deaths-marriages' },
      { name: 'Canterbury Register Office', address: '16A Watling Street, Canterbury CT1 2UT', phone: '03000 419494', url: 'https://www.kent.gov.uk/births-deaths-marriages' },
      { name: 'Tunbridge Wells Register Office', address: 'The Amelia Scott, Mount Pleasant Road, Tunbridge Wells TN1 1QQ', phone: '03000 419494', url: 'https://www.kent.gov.uk/births-deaths-marriages' },
    ],
    councilName: 'Kent County Council',
    councilPhone: '03000 414141',
    councilUrl: 'https://www.kent.gov.uk',
    registrationDeadlineDays: 5,
    majorTowns: ['Maidstone', 'Canterbury', 'Tunbridge Wells', 'Dover', 'Ashford'],
  },
  {
    slug: 'lancashire',
    name: 'Lancashire',
    nation: 'England',
    registrarOffices: [
      { name: 'Preston Register Office', address: 'Christ Church Precinct, Lancaster Road, Preston PR1 1LA', phone: '0300 123 6701', url: 'https://www.lancashire.gov.uk/births-deaths-marriages' },
      { name: 'Lancaster Register Office', address: 'Lancaster Town Hall, Dalton Square, Lancaster LA1 1PJ', phone: '0300 123 6701', url: 'https://www.lancashire.gov.uk/births-deaths-marriages' },
      { name: 'Burnley Register Office', address: 'Town Hall, Manchester Road, Burnley BB11 1JA', phone: '0300 123 6701', url: 'https://www.lancashire.gov.uk/births-deaths-marriages' },
    ],
    councilName: 'Lancashire County Council',
    councilPhone: '0300 123 6701',
    councilUrl: 'https://www.lancashire.gov.uk',
    registrationDeadlineDays: 5,
    majorTowns: ['Preston', 'Lancaster', 'Burnley', 'Blackburn', 'Accrington'],
  },
  {
    slug: 'leicestershire',
    name: 'Leicestershire',
    nation: 'England',
    registrarOffices: [
      { name: 'Leicester Register Office', address: 'Town Hall, Town Hall Square, Leicester LE1 9BG', phone: '0116 454 1005', url: 'https://www.leicester.gov.uk/births-deaths-marriages' },
      { name: 'Loughborough Register Office', address: 'Woodgate Chambers, 70 Woodgate, Loughborough LE11 2TZ', phone: '0116 305 6565', url: 'https://www.leicestershire.gov.uk/births-deaths-marriages' },
    ],
    councilName: 'Leicestershire County Council',
    councilPhone: '0116 232 3232',
    councilUrl: 'https://www.leicestershire.gov.uk',
    registrationDeadlineDays: 5,
    majorTowns: ['Leicester', 'Loughborough', 'Hinckley', 'Melton Mowbray', 'Market Harborough'],
  },
  {
    slug: 'lincolnshire',
    name: 'Lincolnshire',
    nation: 'England',
    registrarOffices: [
      { name: 'Lincoln Register Office', address: 'County Offices, Newland, Lincoln LN1 1YL', phone: '01522 782244', url: 'https://www.lincolnshire.gov.uk/births-deaths-marriages' },
      { name: 'Boston Register Office', address: 'Municipal Buildings, West Street, Boston PE21 8QR', phone: '01522 782244', url: 'https://www.lincolnshire.gov.uk/births-deaths-marriages' },
    ],
    councilName: 'Lincolnshire County Council',
    councilPhone: '01522 552222',
    councilUrl: 'https://www.lincolnshire.gov.uk',
    registrationDeadlineDays: 5,
    majorTowns: ['Lincoln', 'Boston', 'Grantham', 'Skegness', 'Spalding'],
  },
  {
    slug: 'merseyside',
    name: 'Merseyside',
    nation: 'England',
    registrarOffices: [
      { name: 'Liverpool Register Office', address: 'St George\'s Hall, Lime Street, Liverpool L1 1JJ', phone: '0151 233 3004', url: 'https://www.liverpool.gov.uk/births-deaths-marriages' },
      { name: 'Birkenhead Register Office', address: 'Town Hall, Mortimer Street, Birkenhead CH41 5HP', phone: '0151 666 3665', url: 'https://www.wirral.gov.uk/births-deaths-marriages' },
      { name: 'Southport Register Office', address: 'Town Hall, Lord Street, Southport PR8 1DA', phone: '0151 934 4128', url: 'https://www.sefton.gov.uk/births-deaths-marriages' },
    ],
    councilName: 'Liverpool City Council',
    councilPhone: '0151 233 3000',
    councilUrl: 'https://www.liverpool.gov.uk',
    registrationDeadlineDays: 5,
    majorTowns: ['Liverpool', 'Birkenhead', 'Southport', 'St Helens', 'Bootle'],
    localNotes: 'Merseyside has five metropolitan boroughs (Liverpool, Wirral, Sefton, Knowsley, and St Helens), each with its own register office.',
  },
  {
    slug: 'norfolk',
    name: 'Norfolk',
    nation: 'England',
    registrarOffices: [
      { name: 'Norwich Register Office', address: 'County Hall, Martineau Lane, Norwich NR1 2DH', phone: '0344 800 8020', url: 'https://www.norfolk.gov.uk/births-deaths-marriages' },
      { name: 'King\'s Lynn Register Office', address: 'Thoresby College, Queen Street, King\'s Lynn PE30 1HX', phone: '0344 800 8020', url: 'https://www.norfolk.gov.uk/births-deaths-marriages' },
    ],
    councilName: 'Norfolk County Council',
    councilPhone: '0344 800 8020',
    councilUrl: 'https://www.norfolk.gov.uk',
    registrationDeadlineDays: 5,
    majorTowns: ['Norwich', 'King\'s Lynn', 'Great Yarmouth', 'Thetford', 'Dereham'],
  },
  {
    slug: 'northamptonshire',
    name: 'Northamptonshire',
    nation: 'England',
    registrarOffices: [
      { name: 'Northampton Register Office', address: 'The Guildhall, St Giles\' Square, Northampton NN1 1DE', phone: '0300 126 7000', url: 'https://www.westnorthants.gov.uk/births-deaths-marriages' },
      { name: 'Kettering Register Office', address: 'Bowling Green Road, Kettering NN15 7QX', phone: '0300 126 3000', url: 'https://www.northnorthants.gov.uk/births-deaths-marriages' },
    ],
    councilName: 'West Northamptonshire Council',
    councilPhone: '0300 126 7000',
    councilUrl: 'https://www.westnorthants.gov.uk',
    registrationDeadlineDays: 5,
    majorTowns: ['Northampton', 'Kettering', 'Corby', 'Wellingborough', 'Daventry'],
  },
  {
    slug: 'northumberland',
    name: 'Northumberland',
    nation: 'England',
    registrarOffices: [
      { name: 'Morpeth Register Office', address: 'County Hall, Morpeth NE61 2EF', phone: '0345 600 6400', url: 'https://www.northumberland.gov.uk/births-deaths-marriages' },
      { name: 'Alnwick Register Office', address: 'Allerburn House, Alnwick NE66 1YY', phone: '0345 600 6400', url: 'https://www.northumberland.gov.uk/births-deaths-marriages' },
    ],
    councilName: 'Northumberland County Council',
    councilPhone: '0345 600 6400',
    councilUrl: 'https://www.northumberland.gov.uk',
    registrationDeadlineDays: 5,
    majorTowns: ['Morpeth', 'Alnwick', 'Hexham', 'Berwick-upon-Tweed', 'Blyth'],
  },
  {
    slug: 'north-yorkshire',
    name: 'North Yorkshire',
    nation: 'England',
    registrarOffices: [
      { name: 'Northallerton Register Office', address: 'County Hall, Northallerton DL7 8AD', phone: '01609 780780', url: 'https://www.northyorks.gov.uk/births-deaths-marriages' },
      { name: 'York Register Office', address: 'West Offices, Station Rise, York YO1 6GA', phone: '01904 554455', url: 'https://www.york.gov.uk/births-deaths-marriages' },
      { name: 'Harrogate Register Office', address: '36 Victoria Avenue, Harrogate HG1 5PR', phone: '01609 780780', url: 'https://www.northyorks.gov.uk/births-deaths-marriages' },
    ],
    councilName: 'North Yorkshire Council',
    councilPhone: '01609 780780',
    councilUrl: 'https://www.northyorks.gov.uk',
    registrationDeadlineDays: 5,
    majorTowns: ['York', 'Harrogate', 'Scarborough', 'Northallerton', 'Skipton'],
  },
  {
    slug: 'nottinghamshire',
    name: 'Nottinghamshire',
    nation: 'England',
    registrarOffices: [
      { name: 'Nottingham Register Office', address: 'Shakespeare Street, Nottingham NG1 4FQ', phone: '0115 876 2424', url: 'https://www.nottinghamcity.gov.uk/births-deaths-marriages' },
      { name: 'Mansfield Register Office', address: 'Civic Centre, Chesterfield Road South, Mansfield NG19 7BH', phone: '0300 500 80 80', url: 'https://www.nottinghamshire.gov.uk/births-deaths-marriages' },
    ],
    councilName: 'Nottinghamshire County Council',
    councilPhone: '0300 500 80 80',
    councilUrl: 'https://www.nottinghamshire.gov.uk',
    registrationDeadlineDays: 5,
    majorTowns: ['Nottingham', 'Mansfield', 'Newark-on-Trent', 'Worksop', 'Beeston'],
  },
  {
    slug: 'oxfordshire',
    name: 'Oxfordshire',
    nation: 'England',
    registrarOffices: [
      { name: 'Oxford Register Office', address: '1 Tidmarsh Lane, Oxford OX1 1NS', phone: '01865 815482', url: 'https://www.oxfordshire.gov.uk/births-deaths-marriages' },
      { name: 'Banbury Register Office', address: 'Bodicote House, White Post Road, Bodicote, Banbury OX15 4AA', phone: '01865 815482', url: 'https://www.oxfordshire.gov.uk/births-deaths-marriages' },
    ],
    councilName: 'Oxfordshire County Council',
    councilPhone: '01865 792422',
    councilUrl: 'https://www.oxfordshire.gov.uk',
    registrationDeadlineDays: 5,
    majorTowns: ['Oxford', 'Banbury', 'Abingdon', 'Witney', 'Bicester'],
  },
  {
    slug: 'shropshire',
    name: 'Shropshire',
    nation: 'England',
    registrarOffices: [
      { name: 'Shrewsbury Register Office', address: 'The Shirehall, Abbey Foregate, Shrewsbury SY2 6ND', phone: '0345 678 9016', url: 'https://www.shropshire.gov.uk/births-deaths-marriages' },
      { name: 'Telford Register Office', address: 'Civic Offices, Telford TF3 4JA', phone: '01952 382555', url: 'https://www.telford.gov.uk/births-deaths-marriages' },
    ],
    councilName: 'Shropshire Council',
    councilPhone: '0345 678 9000',
    councilUrl: 'https://www.shropshire.gov.uk',
    registrationDeadlineDays: 5,
    majorTowns: ['Shrewsbury', 'Telford', 'Oswestry', 'Bridgnorth', 'Market Drayton'],
  },
  {
    slug: 'somerset',
    name: 'Somerset',
    nation: 'England',
    registrarOffices: [
      { name: 'Taunton Register Office', address: 'County Hall, Taunton TA1 4DY', phone: '0300 123 2224', url: 'https://www.somerset.gov.uk/births-deaths-marriages' },
      { name: 'Bath Register Office', address: 'The Guildhall, High Street, Bath BA1 5AW', phone: '01225 477234', url: 'https://www.bathnes.gov.uk/births-deaths-marriages' },
    ],
    councilName: 'Somerset Council',
    councilPhone: '0300 123 2224',
    councilUrl: 'https://www.somerset.gov.uk',
    registrationDeadlineDays: 5,
    majorTowns: ['Taunton', 'Bath', 'Yeovil', 'Bridgwater', 'Weston-super-Mare'],
  },
  {
    slug: 'south-yorkshire',
    name: 'South Yorkshire',
    nation: 'England',
    registrarOffices: [
      { name: 'Sheffield Register Office', address: 'Town Hall, Pinstone Street, Sheffield S1 2HH', phone: '0114 273 4567', url: 'https://www.sheffield.gov.uk/births-deaths-marriages' },
      { name: 'Doncaster Register Office', address: 'Doncaster Council, Civic Office, Waterdale, Doncaster DN1 3BU', phone: '01302 734050', url: 'https://www.doncaster.gov.uk/births-deaths-marriages' },
      { name: 'Barnsley Register Office', address: 'Town Hall, Church Street, Barnsley S70 2TA', phone: '01226 773555', url: 'https://www.barnsley.gov.uk/births-deaths-marriages' },
    ],
    councilName: 'Sheffield City Council',
    councilPhone: '0114 273 4567',
    councilUrl: 'https://www.sheffield.gov.uk',
    registrationDeadlineDays: 5,
    majorTowns: ['Sheffield', 'Doncaster', 'Barnsley', 'Rotherham', 'Mexborough'],
    localNotes: 'South Yorkshire has four metropolitan boroughs (Sheffield, Doncaster, Barnsley, and Rotherham), each with its own register office.',
  },
  {
    slug: 'staffordshire',
    name: 'Staffordshire',
    nation: 'England',
    registrarOffices: [
      { name: 'Stafford Register Office', address: 'County Buildings, Martin Street, Stafford ST16 2LH', phone: '0300 111 8000', url: 'https://www.staffordshire.gov.uk/births-deaths-marriages' },
      { name: 'Stoke-on-Trent Register Office', address: 'Town Hall, Glebe Street, Stoke-on-Trent ST4 1HH', phone: '01782 234567', url: 'https://www.stoke.gov.uk/births-deaths-marriages' },
      { name: 'Burton Register Office', address: 'Town Hall, King Edward Place, Burton upon Trent DE14 2EB', phone: '0300 111 8000', url: 'https://www.staffordshire.gov.uk/births-deaths-marriages' },
    ],
    councilName: 'Staffordshire County Council',
    councilPhone: '0300 111 8000',
    councilUrl: 'https://www.staffordshire.gov.uk',
    registrationDeadlineDays: 5,
    majorTowns: ['Stafford', 'Stoke-on-Trent', 'Burton upon Trent', 'Lichfield', 'Tamworth'],
  },
  {
    slug: 'suffolk',
    name: 'Suffolk',
    nation: 'England',
    registrarOffices: [
      { name: 'Ipswich Register Office', address: 'Endeavour House, 8 Russell Road, Ipswich IP1 2BX', phone: '0345 607 2050', url: 'https://www.suffolk.gov.uk/births-deaths-marriages' },
      { name: 'Bury St Edmunds Register Office', address: 'Thingoe Hill, Bury St Edmunds IP33 1UR', phone: '0345 607 2050', url: 'https://www.suffolk.gov.uk/births-deaths-marriages' },
    ],
    councilName: 'Suffolk County Council',
    councilPhone: '0345 606 6067',
    councilUrl: 'https://www.suffolk.gov.uk',
    registrationDeadlineDays: 5,
    majorTowns: ['Ipswich', 'Bury St Edmunds', 'Lowestoft', 'Felixstowe', 'Sudbury'],
  },
  {
    slug: 'surrey',
    name: 'Surrey',
    nation: 'England',
    registrarOffices: [
      { name: 'Guildford Register Office', address: 'Artington House, Portsmouth Road, Guildford GU3 1LZ', phone: '01483 404850', url: 'https://www.surreycc.gov.uk/births-deaths-marriages' },
      { name: 'Woking Register Office', address: 'Jubilee House, Woking GU21 5BW', phone: '01483 404850', url: 'https://www.surreycc.gov.uk/births-deaths-marriages' },
      { name: 'Reigate Register Office', address: 'Town Hall, Castlefield Road, Reigate RH2 0SH', phone: '01483 404850', url: 'https://www.surreycc.gov.uk/births-deaths-marriages' },
    ],
    councilName: 'Surrey County Council',
    councilPhone: '03456 009 009',
    councilUrl: 'https://www.surreycc.gov.uk',
    registrationDeadlineDays: 5,
    majorTowns: ['Guildford', 'Woking', 'Reigate', 'Epsom', 'Leatherhead'],
  },
  {
    slug: 'tyne-and-wear',
    name: 'Tyne and Wear',
    nation: 'England',
    registrarOffices: [
      { name: 'Newcastle Register Office', address: 'Civic Centre, Barras Bridge, Newcastle upon Tyne NE1 8QH', phone: '0191 278 7878', url: 'https://www.newcastle.gov.uk/births-deaths-marriages' },
      { name: 'Sunderland Register Office', address: 'Sunderland Civic Centre, Burdon Road, Sunderland SR2 7DN', phone: '0191 520 5553', url: 'https://www.sunderland.gov.uk/births-deaths-marriages' },
      { name: 'Gateshead Register Office', address: 'Civic Centre, Regent Street, Gateshead NE8 1HH', phone: '0191 433 3000', url: 'https://www.gateshead.gov.uk/births-deaths-marriages' },
    ],
    councilName: 'Newcastle City Council',
    councilPhone: '0191 278 7878',
    councilUrl: 'https://www.newcastle.gov.uk',
    registrationDeadlineDays: 5,
    majorTowns: ['Newcastle upon Tyne', 'Sunderland', 'Gateshead', 'South Shields', 'North Shields'],
    localNotes: 'Tyne and Wear has five metropolitan boroughs (Newcastle, Sunderland, Gateshead, North Tyneside, and South Tyneside), each with its own register office.',
  },
  {
    slug: 'warwickshire',
    name: 'Warwickshire',
    nation: 'England',
    registrarOffices: [
      { name: 'Warwick Register Office', address: 'Pageant House, 2 Jury Street, Warwick CV34 4EW', phone: '01926 413743', url: 'https://www.warwickshire.gov.uk/births-deaths-marriages' },
      { name: 'Nuneaton Register Office', address: 'Nuneaton Town Hall, Coton Road, Nuneaton CV11 5AA', phone: '01926 413743', url: 'https://www.warwickshire.gov.uk/births-deaths-marriages' },
    ],
    councilName: 'Warwickshire County Council',
    councilPhone: '01926 410410',
    councilUrl: 'https://www.warwickshire.gov.uk',
    registrationDeadlineDays: 5,
    majorTowns: ['Warwick', 'Nuneaton', 'Rugby', 'Leamington Spa', 'Stratford-upon-Avon'],
  },
  {
    slug: 'west-midlands',
    name: 'West Midlands',
    nation: 'England',
    registrarOffices: [
      { name: 'Birmingham Register Office', address: 'Holliday Street, Birmingham B1 1TJ', phone: '0121 303 5555', url: 'https://www.birmingham.gov.uk/births-deaths-marriages' },
      { name: 'Coventry Register Office', address: 'Cheylesmore Manor House, Manor House Drive, Coventry CV1 2ND', phone: '024 7683 3152', url: 'https://www.coventry.gov.uk/births-deaths-marriages' },
      { name: 'Wolverhampton Register Office', address: 'Civic Centre, St Peter\'s Square, Wolverhampton WV1 1RL', phone: '01902 551155', url: 'https://www.wolverhampton.gov.uk/births-deaths-marriages' },
    ],
    councilName: 'Birmingham City Council',
    councilPhone: '0121 303 1111',
    councilUrl: 'https://www.birmingham.gov.uk',
    registrationDeadlineDays: 5,
    majorTowns: ['Birmingham', 'Coventry', 'Wolverhampton', 'Dudley', 'Walsall'],
    localNotes: 'The West Midlands has seven metropolitan boroughs (Birmingham, Coventry, Wolverhampton, Dudley, Sandwell, Walsall, and Solihull), each with its own register office.',
  },
  {
    slug: 'west-sussex',
    name: 'West Sussex',
    nation: 'England',
    registrarOffices: [
      { name: 'Chichester Register Office', address: 'Orchard Street, Chichester PO19 1DD', phone: '01243 642122', url: 'https://www.westsussex.gov.uk/births-deaths-marriages' },
      { name: 'Crawley Register Office', address: 'Town Hall, The Boulevard, Crawley RH10 1UZ', phone: '01243 642122', url: 'https://www.westsussex.gov.uk/births-deaths-marriages' },
      { name: 'Worthing Register Office', address: 'Portland House, 44 Richmond Road, Worthing BN11 1HS', phone: '01243 642122', url: 'https://www.westsussex.gov.uk/births-deaths-marriages' },
    ],
    councilName: 'West Sussex County Council',
    councilPhone: '01243 777100',
    councilUrl: 'https://www.westsussex.gov.uk',
    registrationDeadlineDays: 5,
    majorTowns: ['Chichester', 'Crawley', 'Worthing', 'Horsham', 'Bognor Regis'],
  },
  {
    slug: 'west-yorkshire',
    name: 'West Yorkshire',
    nation: 'England',
    registrarOffices: [
      { name: 'Leeds Register Office', address: 'Belgrave House, Belgrave Street, Leeds LS2 8DQ', phone: '0113 222 4408', url: 'https://www.leeds.gov.uk/births-deaths-marriages' },
      { name: 'Bradford Register Office', address: 'City Hall, Centenary Square, Bradford BD1 1HY', phone: '01274 432151', url: 'https://www.bradford.gov.uk/births-deaths-marriages' },
      { name: 'Huddersfield Register Office', address: 'Town Hall, Ramsden Street, Huddersfield HD1 2TA', phone: '01484 221400', url: 'https://www.kirklees.gov.uk/births-deaths-marriages' },
    ],
    councilName: 'Leeds City Council',
    councilPhone: '0113 222 4444',
    councilUrl: 'https://www.leeds.gov.uk',
    registrationDeadlineDays: 5,
    majorTowns: ['Leeds', 'Bradford', 'Huddersfield', 'Halifax', 'Wakefield'],
    localNotes: 'West Yorkshire has five metropolitan boroughs (Leeds, Bradford, Kirklees, Calderdale, and Wakefield), each with its own register office.',
  },
  {
    slug: 'wiltshire',
    name: 'Wiltshire',
    nation: 'England',
    registrarOffices: [
      { name: 'Trowbridge Register Office', address: 'County Hall, Bythesea Road, Trowbridge BA14 8JN', phone: '0300 456 0100', url: 'https://www.wiltshire.gov.uk/births-deaths-marriages' },
      { name: 'Salisbury Register Office', address: 'Bourne Hill, Salisbury SP1 3UZ', phone: '0300 456 0100', url: 'https://www.wiltshire.gov.uk/births-deaths-marriages' },
      { name: 'Swindon Register Office', address: 'Beckhampton Street, Swindon SN1 2JH', phone: '01793 466454', url: 'https://www.swindon.gov.uk/births-deaths-marriages' },
    ],
    councilName: 'Wiltshire Council',
    councilPhone: '0300 456 0100',
    councilUrl: 'https://www.wiltshire.gov.uk',
    registrationDeadlineDays: 5,
    majorTowns: ['Trowbridge', 'Salisbury', 'Swindon', 'Chippenham', 'Devizes'],
  },
  {
    slug: 'worcestershire',
    name: 'Worcestershire',
    nation: 'England',
    registrarOffices: [
      { name: 'Worcester Register Office', address: 'County Hall, Spetchley Road, Worcester WR5 2NP', phone: '01905 822744', url: 'https://www.worcestershire.gov.uk/births-deaths-marriages' },
      { name: 'Kidderminster Register Office', address: 'Town Hall, Vicar Street, Kidderminster DY10 1DB', phone: '01905 822744', url: 'https://www.worcestershire.gov.uk/births-deaths-marriages' },
    ],
    councilName: 'Worcestershire County Council',
    councilPhone: '01905 765765',
    councilUrl: 'https://www.worcestershire.gov.uk',
    registrationDeadlineDays: 5,
    majorTowns: ['Worcester', 'Kidderminster', 'Redditch', 'Bromsgrove', 'Evesham'],
  },

  // ===== WALES (8) =====
  {
    slug: 'gwynedd',
    name: 'Gwynedd',
    nation: 'Wales',
    registrarOffices: [
      { name: 'Caernarfon Register Office', address: 'Council Offices, Shirehall Street, Caernarfon LL55 1SH', phone: '01286 679535', url: 'https://www.gwynedd.llyw.cymru/births-deaths-marriages' },
      { name: 'Dolgellau Register Office', address: 'Council Offices, Cader Road, Dolgellau LL40 2SW', phone: '01341 424300', url: 'https://www.gwynedd.llyw.cymru/births-deaths-marriages' },
    ],
    councilName: 'Gwynedd Council',
    councilPhone: '01766 771000',
    councilUrl: 'https://www.gwynedd.llyw.cymru',
    registrationDeadlineDays: 5,
    majorTowns: ['Caernarfon', 'Bangor', 'Dolgellau', 'Pwllheli', 'Blaenau Ffestiniog'],
    localNotes: 'Gwynedd Council provides services in both Welsh and English. Staff at register offices are bilingual.',
  },
  {
    slug: 'powys',
    name: 'Powys',
    nation: 'Wales',
    registrarOffices: [
      { name: 'Llandrindod Wells Register Office', address: 'County Hall, Llandrindod Wells LD1 5LG', phone: '01597 826026', url: 'https://www.powys.gov.uk/births-deaths-marriages' },
      { name: 'Newtown Register Office', address: 'The Park, Newtown SY16 2NZ', phone: '01686 611200', url: 'https://www.powys.gov.uk/births-deaths-marriages' },
    ],
    councilName: 'Powys County Council',
    councilPhone: '01597 826000',
    councilUrl: 'https://www.powys.gov.uk',
    registrationDeadlineDays: 5,
    majorTowns: ['Llandrindod Wells', 'Newtown', 'Brecon', 'Welshpool', 'Ystradgynlais'],
    localNotes: 'Powys is the largest county in Wales by area but the most sparsely populated. Some registrar offices may require longer appointment lead times.',
  },
  {
    slug: 'dyfed',
    name: 'Dyfed',
    nation: 'Wales',
    registrarOffices: [
      { name: 'Carmarthen Register Office', address: 'Parc Myrddin, Richmond Terrace, Carmarthen SA31 1DS', phone: '01267 228228', url: 'https://www.carmarthenshire.gov.wales/births-deaths-marriages' },
      { name: 'Haverfordwest Register Office', address: 'County Hall, Haverfordwest SA61 1TP', phone: '01437 775850', url: 'https://www.pembrokeshire.gov.uk/births-deaths-marriages' },
      { name: 'Aberystwyth Register Office', address: 'Canolfan Rheidol, Aberystwyth SY23 1AS', phone: '01545 572100', url: 'https://www.ceredigion.gov.uk/births-deaths-marriages' },
    ],
    councilName: 'Carmarthenshire County Council',
    councilPhone: '01267 234567',
    councilUrl: 'https://www.carmarthenshire.gov.wales',
    registrationDeadlineDays: 5,
    majorTowns: ['Carmarthen', 'Haverfordwest', 'Aberystwyth', 'Llanelli', 'Milford Haven'],
    localNotes: 'Dyfed covers three modern local authority areas: Carmarthenshire, Pembrokeshire, and Ceredigion. Each has its own register office and council.',
  },
  {
    slug: 'west-glamorgan',
    name: 'West Glamorgan',
    nation: 'Wales',
    registrarOffices: [
      { name: 'Swansea Register Office', address: 'County Hall, Oystermouth Road, Swansea SA1 3SN', phone: '01792 636363', url: 'https://www.swansea.gov.uk/births-deaths-marriages' },
      { name: 'Neath Register Office', address: 'Civic Centre, Neath SA11 3QZ', phone: '01639 686868', url: 'https://www.npt.gov.uk/births-deaths-marriages' },
    ],
    councilName: 'City and County of Swansea Council',
    councilPhone: '01792 636000',
    councilUrl: 'https://www.swansea.gov.uk',
    registrationDeadlineDays: 5,
    majorTowns: ['Swansea', 'Neath', 'Port Talbot', 'Mumbles', 'Gorseinon'],
  },
  {
    slug: 'mid-glamorgan',
    name: 'Mid Glamorgan',
    nation: 'Wales',
    registrarOffices: [
      { name: 'Pontypridd Register Office', address: 'The Old Library, Morgan Street, Pontypridd CF37 2DL', phone: '01443 494024', url: 'https://www.rctcbc.gov.uk/births-deaths-marriages' },
      { name: 'Bridgend Register Office', address: 'Civic Offices, Angel Street, Bridgend CF31 4WB', phone: '01656 643643', url: 'https://www.bridgend.gov.uk/births-deaths-marriages' },
      { name: 'Merthyr Tydfil Register Office', address: 'Castle House, Glebeland Street, Merthyr Tydfil CF47 8AU', phone: '01685 725282', url: 'https://www.merthyr.gov.uk/births-deaths-marriages' },
    ],
    councilName: 'Rhondda Cynon Taf County Borough Council',
    councilPhone: '01443 425001',
    councilUrl: 'https://www.rctcbc.gov.uk',
    registrationDeadlineDays: 5,
    majorTowns: ['Pontypridd', 'Bridgend', 'Merthyr Tydfil', 'Aberdare', 'Caerphilly'],
    localNotes: 'Mid Glamorgan covers three modern local authority areas: Rhondda Cynon Taf, Bridgend, and Merthyr Tydfil. Each has its own register office.',
  },
  {
    slug: 'south-glamorgan',
    name: 'South Glamorgan',
    nation: 'Wales',
    registrarOffices: [
      { name: 'Cardiff Register Office', address: 'City Hall, Cathays Park, Cardiff CF10 3ND', phone: '029 2087 1680', url: 'https://www.cardiff.gov.uk/births-deaths-marriages' },
      { name: 'Barry Register Office', address: 'Civic Offices, Holton Road, Barry CF63 4RU', phone: '01446 700111', url: 'https://www.valeofglamorgan.gov.uk/births-deaths-marriages' },
    ],
    councilName: 'Cardiff Council',
    councilPhone: '029 2087 2087',
    councilUrl: 'https://www.cardiff.gov.uk',
    registrationDeadlineDays: 5,
    majorTowns: ['Cardiff', 'Barry', 'Penarth', 'Dinas Powys', 'Llantwit Major'],
    localNotes: 'South Glamorgan covers Cardiff and the Vale of Glamorgan. Cardiff is the Welsh capital and its register office handles a high volume of registrations.',
  },
  {
    slug: 'gwent',
    name: 'Gwent',
    nation: 'Wales',
    registrarOffices: [
      { name: 'Newport Register Office', address: 'Civic Centre, Godfrey Road, Newport NP20 4UR', phone: '01633 656656', url: 'https://www.newport.gov.uk/births-deaths-marriages' },
      { name: 'Cwmbran Register Office', address: 'Pontypool and Blaenavon Civic Centre, Pontypool NP4 6YB', phone: '01495 762200', url: 'https://www.torfaen.gov.uk/births-deaths-marriages' },
      { name: 'Abergavenny Register Office', address: 'County Hall, Croesyceiliog, Cwmbran NP44 2XH', phone: '01873 735885', url: 'https://www.monmouthshire.gov.uk/births-deaths-marriages' },
    ],
    councilName: 'Newport City Council',
    councilPhone: '01633 656656',
    councilUrl: 'https://www.newport.gov.uk',
    registrationDeadlineDays: 5,
    majorTowns: ['Newport', 'Cwmbran', 'Abergavenny', 'Pontypool', 'Ebbw Vale'],
    localNotes: 'Gwent covers five modern local authority areas: Newport, Torfaen, Monmouthshire, Blaenau Gwent, and Caerphilly. Each has its own register office.',
  },
  {
    slug: 'clwyd',
    name: 'Clwyd',
    nation: 'Wales',
    registrarOffices: [
      { name: 'Wrexham Register Office', address: 'Crown Buildings, 31 Chester Street, Wrexham LL13 8BG', phone: '01978 292037', url: 'https://www.wrexham.gov.uk/births-deaths-marriages' },
      { name: 'Rhyl Register Office', address: 'Council Offices, Russell House, Churton Road, Rhyl LL18 3DP', phone: '01824 708098', url: 'https://www.denbighshire.gov.uk/births-deaths-marriages' },
      { name: 'Mold Register Office', address: 'County Hall, Mold CH7 6NB', phone: '01352 703333', url: 'https://www.flintshire.gov.uk/births-deaths-marriages' },
    ],
    councilName: 'Wrexham County Borough Council',
    councilPhone: '01978 292000',
    councilUrl: 'https://www.wrexham.gov.uk',
    registrationDeadlineDays: 5,
    majorTowns: ['Wrexham', 'Rhyl', 'Mold', 'Denbigh', 'Colwyn Bay'],
    localNotes: 'Clwyd covers three modern local authority areas: Wrexham, Denbighshire, and Flintshire. Each has its own register office and council.',
  },
];

export function getCountyBySlug(slug: string): CountyData | undefined {
  return counties.find(c => c.slug === slug);
}

export function getAllCounties(): CountyData[] {
  return counties;
}

export function getCountiesByNation(nation: string): CountyData[] {
  return counties.filter(c => c.nation === nation);
}
